### ISSUE TITLE
[MSVC] Vim won't compile after updating from Python 3.13.3 to 3.13.4

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#17509]
### Steps to reproduce

I noticed that the update from Python 3.13.3 to 3.13.4 on Windows breaks Vim's build, because the update basically set `#define Py_GIL_DISABLED 1` in `pyconfig.h` which was commented out in an earlier version, resulting in the "limited API" not working anymore. I don't know the reason behind using the "limited API", and AFAIK it will be optional in Python 4 whenever that happens, but this should probably be addressed.

### Expected behaviour

`nmake` just works.

### Version of Vim

9.1.1446

### Environment

Windows 10, Visual Studio 2022, Python installed from Scoop (which uses the upstream installers from python.org).

### Logs and stack traces

```shell
if_python3.c
[redacted]\scoop\apps\python313\current\Include\Python.h(51): fatal error C1189: #error:  "The limited API is not currently supported in the free-threaded build"
NMAKE :  U1077: "cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DHAVE_STDINT_H  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "..\..\libs\libsodium-1.0.20\include"  -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP    -DWINVER=0x0601 -D_WIN32_WINNT=0x0601  /source-charset:utf-8 /MP /Ox /GL -DNDEBUG /arch:SSE2 /MD -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\"  -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA  -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON  -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3  -DDYNAMIC_PYTHON3_DLL=\"python3.dll\" -DDYNAMIC_PYTHON3_STABLE_ABI -DFEAT_MZSCHEME -I "..\..\libs\racket-8.17\include" -DDYNAMIC_MZSCHEME  -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\"  -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl540.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY  -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby340.dll\" -DRUBY_VERSION=34 -DMSWINPS -DFEAT_HUGE /Fd.\ObjGXULYHTRZVi386/ /Zi /Fo.\ObjGXULYHTRZVi386/ /I "[redacted]\scoop\apps\python313\current\Include" /I "[redacted]\scoop\apps\python313\current\PC" -DPy_LIMITED_API=0x3080000 if_python3.c": Rückgabe-Code "0x2"
Stop.
```

**Comment by chrisbra** [comment]
I think you may need to remove the `-DDYNAMIC_PYTHON3_STABLE_ABI` . Don't know why this python does not support it, probably because of the GIL refactoring that they have been doing

**Comment by dertuxmalwieder** [comment]
`-DDYNAMIC_PYTHON3_STABLE_ABI` is [automatically added](https://github.com/vim/vim/blob/master/src/Make_mvc.mak#L1002) for dynamic Python3 and there is no (obvious) way to change that on the command line.

**Comment by chrisbra** [comment]
I suppose you could pass `-DYNAMIC_PYTHON3_STABLE_ABI=no` no? In any case, I am wondering if we should check back with the Python developers for this.

**Comment by dertuxmalwieder** [comment]
I suppose I could also statically link Python, which I try to avoid in my builds. :-)

**Comment by cgohlke** [comment]
It's a [bug in cpython](https://github.com/python/cpython/issues/135151)

**Comment by chrisbra** [comment]
ah, so it's a bug. Let's close it here then as won't do and await Python 3.13.5 then. Thanks both!

**Comment by dertuxmalwieder** [comment]
Oh, thank you!

**Comment by chrisbra** [comment]
Seems we hit this issue now in Github actions [runners](https://github.com/actions/runner-images/releases/tag/win22%2F20250609.2) as [well](https://github.com/vim/vim/actions/runs/15570836046/job/43851117962#step:9:233)

Gosh not only those failing apt repositories, now also this :/

**Comment by dertuxmalwieder** [comment]
There are reasons why I haven't just hid my build pipeline behind a giant CI. ;-)

**Comment by chrisbra** [comment]
Github Actions [Bug](https://github.com/actions/runner-images/issues/12377)

**Comment by dertuxmalwieder** [comment]
Python 3.13.5 is out, fixing it.
