### ISSUE TITLE
failed to build with dynamic ruby 1.9.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#49]
```
What steps will reproduce the problem?
1.
    ./configure --prefix=/usr --localstatedir=/var/lib/vim \
        --mandir=/usr/share/man \
        --with-features=huge --enable-gpm --enable-acl --with-x=no \
        --disable-gui --enable-multibyte --enable-cscope \
        --disable-netbeans --enable-perlinterp=dynamic \
        --enable-pythoninterp=dynamic --enable-python3interp=dynamic \
        --enable-rubyinterp=dynamic --enable-luainterp=dynamic

2. make

What is the expected output? What do you see instead?
success build


What version of the product are you using? On what operating system?
7.3.410, archlinux

Please provide any additional information below.

build ends with:

objects/if_ruby.o: In function `window_s_aref':
if_ruby.c:(.text+0x31f): undefined reference to `rb_fix2int'
if_ruby.c:(.text+0x361): undefined reference to `rb_num2int'
objects/if_ruby.o: In function `buffer_s_aref':
if_ruby.c:(.text+0x3cf): undefined reference to `rb_fix2int'
if_ruby.c:(.text+0x419): undefined reference to `rb_num2int'
objects/if_ruby.o: In function `window_set_width':
if_ruby.c:(.text+0x105d): undefined reference to `rb_num2int'
if_ruby.c:(.text+0x1089): undefined reference to `rb_fix2int'
objects/if_ruby.o: In function `window_set_height':
if_ruby.c:(.text+0x10cd): undefined reference to `rb_num2int'
if_ruby.c:(.text+0x10f9): undefined reference to `rb_fix2int'
objects/if_ruby.o: In function `window_set_cursor':
if_ruby.c:(.text+0x1170): undefined reference to `rb_num2uint'
collect2: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [vim] Error 1
make[1]: Leaving directory `/build/src/vim-build/src'
make: *** [first] Error 2

```

Original issue reported on code.google.com by `Ike.Devo...@gmail.com` on 25 Jan 2012 at 4:10
