### ISSUE TITLE
Vim 8.2.2421 fails to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by chdiza** [vim/vim#7753]
Ubuntu 20.04,  Trying to build vim 8.2.2421 fails as follows:

```
In file included from arglist.c:14:
arglist.c: In function ‘check_arglist_locked’:
arglist.c:29:9: error: ‘e_cannot_change_arglist_recursively’ undeclared (first use in this function); did you mean ‘e_cannot_change_list_item’?
   29 |  emsg(_(e_cannot_change_arglist_recursively));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vim.h:548:25: note: in definition of macro ‘_’
  548 | # define _(x) ((char *)(x))
      |                         ^
arglist.c:29:9: note: each undeclared identifier is reported only once for each function it appears in
   29 |  emsg(_(e_cannot_change_arglist_recursively));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
vim.h:548:25: note: in definition of macro ‘_’
  548 | # define _(x) ((char *)(x))
      |                         ^
make[1]: *** [Makefile:3143: objects/arglist.o] Error 1
make[1]: Leaving directory '/opt/bld/vim/src'
make: *** [Makefile:29: first] Error 2
```

The problem must be sometime within the last <10 patchlevels, because I build successfully within the last couple of days.

**Comment by shermanikk** [comment]
I'm getting the same error on MacOS via Homebrew on my M1 MacBook Air, so it must be fairly universal. 

```
HEAD is now at 5ed58c7 patch 8.2.2421: double free when using autocommand with "argdel"
==> ./configure --prefix=/opt/homebrew --mandir=/opt/homebrew/Cellar/vim/HEAD-5ed58c7/share/man --enable-multibyte --with-tlib=ncurses --with-compiledby=Homebrew --enable-cscope --enable-terminal --enable-perlinterp --enable-ruby
==> make
Last 15 lines from ~/Library/Logs/Homebrew/vim/02.make:
clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1        -o objects/blowfish.o blowfish.c
arglist.c:29:9: error: use of undeclared identifier 'e_cannot_change_arglist_recursively'; did you mean 'e_cannot_change_list_item'?
        emsg(_(e_cannot_change_arglist_recursively));
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               e_cannot_change_list_item
./vim.h:539:33: note: expanded from macro '_'
#  define _(x) gettext((char *)(x))
                                ^
./errors.h:273:13: note: 'e_cannot_change_list_item' declared here
EXTERN char e_cannot_change_list_item[]
            ^
1 error generated.
make[1]: *** [objects/arglist.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
```

**Comment by Becomebright** [comment]
Same error on Ubuntu 16.04

**Comment by chrisbra** [comment]
looks like this is from https://github.com/vim/vim/releases/tag/v8.2.2421 

and looks like a global configuration `e_cannot_change_arglist_recursively` is missing

**Comment by brammool** [comment]
Fixed by 8.2.2423
