### ISSUE TITLE
Linking problem with 9.0.96

### ISSUE THREAD

**Issue by cecamp** [vim/vim#10805]
### Steps to reproduce

./configure --with-features=huge --enable-gui=gtk3 --enable-perlinterp --enable-pythoninterp --enable-rubyinterp   --enable-cscope

### Expected behaviour

Linker complained about missing DSO from command line; linking failed. Of course, expected behavior is that linking succeeded.

### Version of Vim

Worked with vim 9.0.73; failed when attempting to compile+link vim 9.0.96

### Environment

TERM: xterm-256color
system: Scientific Linux release 7.9 (Nitrogen)
compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
shell: ksh

### Logs and stack traces

```shell
/usr/bin/ld: objects/os_unix.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
//usr/lib64/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
link.sh: Linking failed
gmake: *** [vim] Error 1
```

**Comment by cecamp** [comment]
I should have included the preceding line from the attempt at linking: usr/bin/ld: objects/os_unix.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'

**Comment by ant0sha** [comment]
Same as #10799 ?

**Comment by chrisbra** [comment]
no, it looks like Scientific Linux release 7.9 is too old and does not provide the `timer_settime` function. I guess this is a configure problem?

**Comment by brammool** [comment]
Charles Campbell wrote:

> ### Steps to reproduce
> 
> ./configure --with-features=huge --enable-gui=gtk3 --enable-perlinterp --enable-pythoninterp --enable-rubyinterp   --enable-cscope
> 
> 
> ### Expected behaviour
> 
> Linker complained about missing DSO from command line; linking failed. Of course, expected behavior is that linking succeeded.
> 
> ### Version of Vim
> 
> Worked with vim 9.0.73; failed when attempting to compile+link vim 9.0.96
> 
> ### Environment
> 
> TERM: xterm-256color
> system: Scientific Linux release 7.9 (Nitrogen)
> compiler: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
> shell: ksh
> 
> ### Logs and stack traces
> 
> ```shell
> /usr/bin/ld: objects/os_unix.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
> //usr/lib64/librt.so.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> link.sh: Linking failed
> gmake: *** [vim] Error 1
> ```

Others report something similar.  Patch 9.0.0065 is blamed.
Unfortunately, I cannot reproduce this and I cannot guess what the
problem is.

Can you check the LIBS line in src/auto/config.mk ?  It probably should
include "-lrt".  If not, then try adding it (and run "make", not
"configure").

-- 
hundred-and-one symptoms of being an internet addict:
164. You got out to buy software, instead of going out for a beer.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by brammool** [comment]
Christian wrote:

> no, it looks like Scientific Linux release 7.9 is too old and does not
> provide the `timer_settime` function. I guess this is a configure
> problem? 

Hmm, the configure check should detect that timer_settime() isn't
working.  Is the configure check broken?  It appears that it was working
before 9.0.0065, and I don't see what that patch could break.

I did just fix a warning, caused by a missing include file, but I doubt
it makes any difference.

-- 
"Hit any key to continue" does _not_ mean you can hit the on/off button!

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by cecamp** [comment]
Putting -lrt using EXTRA_LIBS in the Makefile allowed vim to link correctly!

**Comment by chrisbra** [comment]
I suppose efffa5360ebb2b6919c5eb1998c5df4c8849a407 fixes this then.

**Comment by cecamp** [comment]
Yes, that patch fixes it, and vim 9.0.103 linked just fine. Closing...
