### ISSUE TITLE
Support for ruby 1.8 broken since 8.1.0735

### ISSUE THREAD

**Issue by tgc** [vim/vim#3883]
Since 8.1.0735 builds with Ruby 1.8.x as shipped with RHEL 6 and older are failling:

objects/if_ruby.o: In function `vim_blob':
/builddir/build/BUILD/vim-8.1.0842/src/if_ruby.c:1265: undefined reference to `rb_str_new_cstr'
collect2: ld returned 1 exit status
link.sh: Linking failed
make: *** [vim] Error 1

I previously built 8.1.0714 with no issues against ruby 1.8.1 (el4), 1.8.5 (el5) and 1.8.7 (el6).
RHEL 7 ships with Ruby 2.0.0 and is not affected.
