### ISSUE TITLE
Support for python 2.3 and 2.4 is broken since 8.1.0735

### ISSUE THREAD

**Issue by tgc** [vim/vim#3888]
Since 8.1.0735 builds with python 2.3 and 2.4 as shipped with RHEL 5 and older are failling: 
```
objects/if_python.o: In function `ConvertToPyObject':
/builddir/build/BUILD/vim-8.1.0853/src/if_py_both.h:6392: undefined reference to `PyBytes_FromStringAndSize'
objects/if_python.o: In function `VimToPython':
/builddir/build/BUILD/vim-8.1.0853/src/if_py_both.h:867: undefined reference to `PyBytes_FromStringAndSize'
collect2: ld returned 1 exit status
link.sh: Linking failed
```
I previously built 8.1.0714 with no issues against python 2.3.4 (el4), 2.4.3 (el5). RHEL 6 and later ships python 2.6 or 2.7 and is not affected.

**Comment by brammool** [comment]
Tom G. Christensen wrote:

> Since 8.1.0735 builds with python 2.3 and 2.4 as shipped with RHEL 5 and older are failling: 
> ```
> objects/if_python.o: In function `ConvertToPyObject':
> /builddir/build/BUILD/vim-8.1.0853/src/if_py_both.h:6392: undefined reference to `PyBytes_FromStringAndSize'
> objects/if_python.o: In function `VimToPython':
> /builddir/build/BUILD/vim-8.1.0853/src/if_py_both.h:867: undefined reference to `PyBytes_FromStringAndSize'
> collect2: ld returned 1 exit status
> link.sh: Linking failed
> ```
> I previously built 8.1.0714 with no issues against python 2.3.4 (el4), 2.4.3 (el5). RHEL 6 and later ships python 2.6 or 2.7 and is not affected.

There were no changes to the python interface between 8.1.0714 and
8.1.0735. Did something change in the Python libraries?

-- 
MESKIMEN'S LAW
    There's never time to do it right, but always time to do it over.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by tgc** [comment]
The blob support added in 8.1.0735 also touched if_py_both.h.

https://github.com/vim/vim/commit/6e5ea8d2a995b32bbc5972edc4f827b959f2702f#diff-e30f7b2f6336d31826de211f8f86f376

**Comment by brammool** [comment]
Tom G. Christensen:

> The blob support added in 8.1.0735 also touched if_py_both.h.
> 
> https://github.com/vim/vim/commit/6e5ea8d2a995b32bbc5972edc4f827b959f2702f#diff-e30f7b2f6336d31826de211f8f86f376

Ah, I took your remark too literally and though it was before that
patch.

Perhaps it should use PyString_FromStringAndSize(), but I don't know
since what version PyBytes_FromStringAndSize() is supported.

Yasuhiro, do you know?


-- 
There can't be a crisis today, my schedule is already full.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
It seems that Python 2.6 supports it.
How about this patch?

```diff
--- a/src/if_py_both.h
+++ b/src/if_py_both.h
@@ -93,6 +93,10 @@ static PyObject *py_load_module;
 
 static PyObject *VimError;
 
+#if PY_VERSION_HEX < 0x02060000
+# define PyBytes_FromStringAndSize PyString_FromStringAndSize
+#endif
+
 /*
  * obtain a lock on the Vim data structures
  */
```

**Comment by dpelle** [comment]
In `if_python.c`, I see:
```
#define PyBytes_FromString      PyString_FromString
#define PyBytes_Check		PyString_Check
#define PyBytes_AsStringAndSize PyString_AsStringAndSize
```
By analogy with the other macros, shouldn't it also define this?
```
#define PyBytes_FromStringAndSize      PyString_FromStringAndSize
```

**Comment by k-takata** [comment]
Ah, define it in `if_python.c` is simpler than defining in `if_py_both.h`.

**Comment by k-takata** [comment]
I also found some wrong indents. Please check the following patch:
https://bitbucket.org/k_takata/vim-ktakata-mq/src/9a8036395a7faf1cb2336bf5635c22cc4aab4096/fix-if_python.patch?at=default&fileviewer=file-view-default
