### ISSUE TITLE
Vim-8.2.4127 fails to build with `./configure --with-features=tiny --enable-gui=none --enable-canberra`

### ISSUE THREAD

**Issue by dpelle** [vim/vim#9548]
### Steps to reproduce

Vim-8.2.4127 fails to build on Linux x86_64 (xubuntu-18.04.6) when configured with:
```
$ cd vim/src
$ ./configure --with-features=tiny --enable-gui=none --enable-canberra
$ make
...
  gcc-11   -L/usr/local/lib -Wl,--as-needed 	-o vim objects/alloc.o objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/float.o objects/fold.o objects/getchar.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/list.o objects/locale.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/strings.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9cmds.o objects/vim9compile.o objects/vim9execute.o objects/vim9expr.o objects/vim9instr.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o              objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf  -lselinux -lcanberra -lacl -lattr -lgpm -ldl           
/usr/local/bin/ld: objects/sound.o: in function `get_sound_callback':
/home/pel/sb/vim/src/sound.c:51: undefined reference to `get_callback'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:57: undefined reference to `free_callback'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:62: undefined reference to `set_callback'
/usr/local/bin/ld: objects/sound.o: in function `delete_sound_callback':
/home/pel/sb/vim/src/sound.c:83: undefined reference to `free_callback'
/usr/local/bin/ld: objects/sound.o: in function `invoke_sound_callback':
/home/pel/sb/vim/src/sound.c:170: undefined reference to `call_callback'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:171: undefined reference to `clear_tv'
/usr/local/bin/ld: objects/sound.o: in function `sound_play_common':
/home/pel/sb/vim/src/sound.c:182: undefined reference to `check_for_string_arg'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:195: undefined reference to `tv_get_string'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:210: undefined reference to `tv_get_string'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:213: undefined reference to `tv_get_string'
/usr/local/bin/ld: objects/sound.o: in function `f_sound_stop':
/home/pel/sb/vim/src/sound.c:249: undefined reference to `check_for_number_arg'
/usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:253: undefined reference to `tv_get_number'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
Makefile:2157: recipe for target 'vim' failed
make: *** [vim] Error 1
```

I suppose that all the code related to callbacks in `sound.c` should be disabled
when `FEAT_EVAL` is not defined.

### Expected behaviour

Vim should compile/link successfully.

### Version of Vim

vim-8.2.4127

### Environment

xubuntu-18.04.6

**Comment by brammool** [comment]
Dominique wrote:
j
> ### Steps to reproduce
> 
> Vim-8.2.4127 fails to build on Linux x86_64 (xubuntu-18.04.6) when configured with:
> ```
> $ cd vim/src
> $ ./configure --with-features=tiny --enable-gui=none --enable-canberra
> $ make
> ...
>   gcc-11   -L/usr/local/lib -Wl,--as-needed 	-o vim objects/alloc.o objects/arabic.o objects/arglist.o objects/ ...  objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o              objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf  -lselinux -lcanberra -lacl -lattr -lgpm -ldl           
> /usr/local/bin/ld: objects/sound.o: in function `get_sound_callback':
> /home/pel/sb/vim/src/sound.c:51: undefined reference to `get_callback'
> /usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:57: undefined reference to `free_callback'
> /usr/local/bin/ld: /home/pel/sb/vim/src/sound.c:62: undefined reference to `set_callback'

[...]

> I suppose that all the code related to callbacks in `sound.c` should
> be disabled when `FEAT_EVAL` is not defined.

There is not much use of the sound feature without the eval feature.
I'll add a configure check, like we have for Perl, Lua and a few others.

-- 
A poem:                read aloud:

<> !*''#               Waka waka bang splat tick tick hash,
^"`$$-                 Caret quote back-tick dollar dollar dash,
!*=@$_                 Bang splat equal at dollar under-score,
%*<> ~#4               Percent splat waka waka tilde number four,
&[]../                 Ampersand bracket bracket dot dot slash,
|{,,SYSTEM HALTED      Vertical-bar curly-bracket comma comma CRASH.

Fred Bremmer and Steve Kroese (Calvin College & Seminary of Grand Rapids, MI.)

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///
