### ISSUE TITLE
Linking problem with 9.0.0124

### ISSUE THREAD

**Issue by dga86** [vim/vim#10831]
### Steps to reproduce

./configure vim_cv_timer_create=yes
make

### Expected behaviour

link.sh: Linked fine

### Version of Vim

9.0.0124

### Environment

Ubuntu 20.04.3 LTS
TERM: xterm-256color
Shell: bash
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

Note that the same steps work as expected when using:
Ubuntu 22.04 LTS
TERM: xterm-256color
Shell: bash
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0

### Logs and stack traces

```shell
link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
  gcc   -L/usr/local/lib -Wl,--as-needed 	-o vim objects/alloc.o objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/float.o objects/fold.o objects/getchar.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/list.o objects/locale.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/strings.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9cmds.o objects/vim9compile.o objects/vim9execute.o objects/vim9expr.o objects/vim9instr.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o  objects/vterm_encoding.o objects/vterm_keyboard.o objects/vterm_mouse.o objects/vterm_parser.o objects/vterm_pen.o objects/vterm_screen.o objects/vterm_state.o objects/vterm_unicode.o objects/vterm_vterm.o         objects/netbeans.o objects/job.o objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o        -lm -ltinfo  -lselinux -ldl           
/usr/bin/ld: objects/os_unix.o: in function `stop_timeout':
vim/src/os_unix.c:8281: undefined reference to `timer_settime'
/usr/bin/ld: objects/os_unix.o: in function `start_timeout':
vim/src/os_unix.c:8321: undefined reference to `timer_create'
vim/src/os_unix.c:8334: undefined reference to `timer_settime'
/usr/bin/ld: objects/os_unix.o: in function `delete_timer':
vim/src/os_unix.c:8349: undefined reference to `timer_delete'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make[1]: *** [Makefile:2112: vim] Error 1
make[1]: Leaving directory 'vim/src'
make: *** [Makefile:29: first] Error 2
```

**Comment by brammool** [comment]
Have you tried running configure without an argument?
You could also try using vim_cv_timer_create_with_lrt

**Comment by brammool** [comment]
What if you run configure without an argument?  What about using "make distclean" first.

Generally, after syncing to head, "make distclean" might be needed, because the configure checks may need to run again for changes in configure or build environment.

**Comment by dga86** [comment]
"make distclean" used.

The reason for using the argument is because oe-core commit [d0c1de084c7ce030d47a428e4bbfbc4ce2996057](https://github.com/openembedded/openembedded-core/commit/d0c1de084c7ce030d47a428e4bbfbc4ce2996057) sets 'vim_cv_timer_create=yes'
I'm just trying to be consistent :)

**Comment by shjinyuan** [comment]
I laso met this problem when I try to build the vim myslef. 
What I did to fix it:
in src/auto/config.mk  , added -lrt at line 27, like: ` LIBS		= -lm -ltinfo -lelf   -lcanberra -ldl -lrt`

Actually I checked the config.ac , in commit 509695c1c3f5c94, Richard had a fix for it, but it not work on my ubuntu 18.04.1
And I can't understand the syntax well, so I can't do a fix for it.

**Comment by dga86** [comment]
> For me it says (somewhere in the configure output): `checking for timer_create without -lrt... (cached) yes` As a result, auto/config.h contains `#define HAVE_TIMER_CREATE 1`
> 
> If that doesn't work for you, try editing auto/config.h to remove that line. If it builds then it means you should not configure with that value.

@brammool 
I also get the mentioned line in the configure output.
Build is ok after remove the `#define HAVE_TIMER_CREATE 1` line.

However, I would assume that the `configure` script should either configure the source properly, or warn if any given arguments are not applicable.

**Comment by brammool** [comment]
If you manually set cache values you have to make sure they are correct.
Instead of 'vim_cv_timer_create=yes' you may need  'vim_cv_timer_create_with_lrt=yes'

**Comment by brammool** [comment]
> I laso met this problem when I try to build the vim myslef. 
> What I did to fix it:
> in src/auto/config.mk  , added -lrt at line 27, like: ` LIBS		= -lm -ltinfo -lelf   -lcanberra -ldl -lrt`
> 
> Actually I checked the config.ac , in commit 509695c1c3f5c94, Richard had a fix for it, but it not work on my ubuntu 18.04.1
> And I can't understand the syntax well, so I can't do a fix for it.

So the configure check appears to work without adding -lrt, but you do
need it to build Vim.  I wonder why the configure check succeeds, since
it does build the test program and runs it.

in src/auto/config.log can you find the output related to
"for timer_create without -lrt" ?

-- 
hundred-and-one symptoms of being an internet addict:
242. You turn down a better-paying job because it doesn't come with
     a free e-mail account.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by dga86** [comment]
$ grep -r "for timer_create without -lrt" src/auto/config.log -C3

configure:12999: gcc -c -g -O2  conftest.c >&5
configure:12999: $? = 0
configure:13000: result: yes
**configure:13009: checking for timer_create without -lrt
configure:13058: result: yes**
configure:13130: checking whether stat() ignores a trailing slash
configure:13169: result: no

**Comment by brammool** [comment]
This doesn't tell us the command that was used.  I suppose it is only added to the log when the compiler outputs something (I get a warning for unused parameter).
You could change the test in auto/configure a bit to trigger a warning, so that we do see the command used for compiling the test program.

**Comment by k-takata** [comment]
What the log looks like if you execute `./configure` without setting `vim_cv_timer_create` and `vim_cv_timer_create_with_lrt`?

**Comment by brammool** [comment]
OK, so the configure script is working.  The problem is passing the wrong argument to configure.  That is not something we can fix, therefore closing.
