### ISSUE TITLE
Failed to build vim

### ISSUE THREAD

**Issue by imbear** [vim/vim#17402]
### Steps to reproduce

```
@call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"

set VIM=d:\vim\vim90
set VCPKG=D:\vcpkg\installed\x64-windows

set PYTHON3_VER=313
set PYTHON3=D:\scoop\apps\python\current

set LUA_VER=54
set LUA=%VCPKG%
set DYNAMIC_LUA=yes

set SODIUM=%VCPKG%
set DYNAMIC_SODIUM=yes

nmake -f Make_mvc.mak DEBUG=no VIMDLL=yes CPU=AMD64 NETBEANS=no IME=yes CSCOPE=no
```

Output:
```
d:\vim-build\vim\src\usercmd.c(545) : fatal error C1001: 内部编译器错误。
(编译器文件“D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.cpp”，第 258 行)
 要解决此问题，请尝试简化或更改上面所列位置附近的程序。
如果可以，请在此处提供重现步骤: https://developercommunity.visualstudio.com
请选择 Visual C++
“帮助”菜单上的“技术支持”命令，或打开技术支持帮助文件来获得详细信息。
   77  link!RaiseException()+0x8a
  link!RaiseException()+0x8a
  link!CloseTypeServerPDB()+0xf3e6b
  link!CloseTypeServerPDB()+0x11a334
  link!InvokeCompilerPassW()+0x7a62a

 NMAKE : fatal error U1077: “link @C:\Users\imbear\AppData\Local\Temp\nm495E.tmp”: 返回代码“0xe06d5034”
Stop.
```

### Expected behaviour

Build vim successfully

### Version of Vim

* 5199567f (HEAD -> master, tag: v9.1.1418

### Environment

Windows 11 Home
Microsoft Visual Studio Community 2022 (64 bit) - Version 17.14.2

### Logs and stack traces

```shell

```

**Comment by chrisbra** [comment]
Translated via ChatGPT: 

> d:\vim-build\vim\src\usercmd.c(545) : fatal error C1001: Internal compiler error.
(Compiler file "D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.cpp", line 258)
To work around this problem, try simplifying or changing the program near the location listed above.
If possible, please provide repro steps here: https://developercommunity.visualstudio.com
Please choose the "Technical Support" command on the "Help" menu in Visual C++,
or open the Technical Support help file for more information.
   77  link!RaiseException()+0x8a


How about you follow the advice given?

**Comment by mrdubya** [comment]
I have reported the failure of 64-bit optimized builds using VS 17.14 to the [MS Dev Community](https://developercommunity.visualstudio.com/t/C1001:-Internal-compiler-error-with-64-b/10918408).

The workarounds for now are to do a debug 64-bit build or an optimised 32-bit version of VIM. One will be slow, the other will have problems if you want to link against other 64-bit DLLs.

**Comment by barcharcraz** [comment]
This is fixed in the next major (non-patch) release of MSVC!
