### ISSUE TITLE
[RHEL 5; Vim 8.0.1451] src/gui_gtk.c:2201: undefined reference to `gtk_entry_get_text_length'

### ISSUE THREAD

**Issue by fusion809** [vim/vim#2605]
Hi,

Vim 8.0.1433 builds fine for my openSUSE Build Service (OBS) RHEL 5 and CentOS 5 build targets, but for 8.0.1451 it fails with the error:

```bash
[  103s]   gcc -L/lib64    -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed 	-o vim objects/arabic.o objects/beval.o objects/buffer.o objects/blowfish.o objects/crypt.o objects/crypt_zip.o objects/dict.o objects/diff.o objects/digraph.o objects/edit.o objects/eval.o objects/evalfunc.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/farsi.o objects/fileio.o objects/fold.o objects/getchar.o objects/hardcopy.o objects/hashtab.o  objects/if_cscope.o objects/if_xcmdsrv.o objects/list.o objects/mark.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/move.o objects/mbyte.o objects/normal.o objects/ops.o objects/option.o objects/os_unix.o objects/pathdef.o objects/popupmnu.o objects/pty.o objects/quickfix.o objects/regexp.o objects/screen.o objects/search.o objects/sha256.o objects/spell.o objects/spellfile.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/ui.o objects/undo.o objects/userfunc.o objects/version.o objects/window.o objects/gui.o objects/gui_gtk.o objects/gui_gtk_x11.o objects/gui_gtk_f.o objects/gui_beval.o  objects/term_encoding.o objects/term_keyboard.o objects/term_mouse.o objects/term_parser.o objects/term_pen.o objects/term_screen.o objects/term_state.o objects/term_unicode.o objects/term_vterm.o    objects/if_python.o   objects/if_ruby.o   objects/netbeans.o objects/channel.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o   -L/lib64 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lpango-1.0 -lcairo -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lnsl  -lselinux  -lacl -lattr           
[  103s] objects/gui_gtk.o: In function `find_replace_dialog_create':
[  103s] /usr/src/redhat/BUILD/vim-8.0.1451/src/gui_gtk.c:2201: undefined reference to `gtk_entry_get_text_length'
[  103s] collect2: ld returned 1 exit status
[  103s] link.sh: Linking failed
[  103s] make: *** [vim] Error 1
```

The complete log is [here](https://gist.github.com/fusion809/0dc2666965af926f5d8493d7ec5ab9ff). For newer build targets the build goes fine. The build options and patches used are contained in this tarball [vim.tar.gz](https://github.com/vim/vim/files/1684287/vim.tar.gz). 

Makes me wonder if recent edits have reduced compatibility with older compilers, although as it does mention GTK+ it could just be older versions of GTK+ 2. 

Thanks for your time,
Brenton

**Comment by tonymec** [comment]
Works for me on openSUSE 42.3 with Vim 8.0.1451, gcc 4.8.5 and GTK2 2.24.31.

What are your versions of gcc ang gtk2? For gcc, ``gcc --version`` is easy enough, but for GTK2 you will probably need to ask ``rpm -qa | grep ^gtk2`` (then find the right line by eyeball) on RedHat, and I don't know if CentOS uses rpm or not.

Best regards,
Tony.

**Comment by nuko8** [comment]
Hmm, according to the build log, the target GTK+ 2 is 2.10.4, which was released on 2007-07-16.  In general, as the current version is 2.24.31, it's too old to guarantee that the latest gvim having new features and bug fixes works well with it.

The current code around `gui_gtk.c:2201` should work with GTK+ >= 2.14.  To support GTK+ 2 older than that, the following patch could fix the issue:
```diff
diff --git a/src/gui_gtk.c b/src/gui_gtk.c
index c1b047974..b4433efd2 100644
--- a/src/gui_gtk.c
+++ b/src/gui_gtk.c
@@ -2144,6 +2144,21 @@ convert_localized_message(char_u **buffer, const char *message)
     return (const char *)*buffer;
 }
 
+    static long
+entry_get_text_length(GtkEntry *entry)
+{
+    g_return_val_if_fail(entry != NULL, 0);
+    g_return_val_if_fail(GTK_IS_ENTRY(entry) == TRUE, 0);
+
+#if GTK_CHECK_VERSION(2,18,0)
+    return gtk_entry_buffer_get_length(gtk_entry_get_buffer(entry));
+#elif GTK_CHECK_VERSION(2,14,0)
+    return gtk_entry_get_text_length(entry);
+#else
+    return g_utf8_strlen(gtk_entry_get_text(entry), -1);
+#endif
+}
+
     static void
 find_replace_dialog_create(char_u *arg, int do_replace)
 {
@@ -2198,10 +2213,9 @@ find_replace_dialog_create(char_u *arg, int do_replace)
 	 * For :promptrepl dialog, give it to 'with' entry if 'what' has an
 	 * non-empty entry; otherwise, to 'what' entry. */
 	gtk_widget_grab_focus(frdp->what);
-	if (do_replace && gtk_entry_get_text_length(GTK_ENTRY(frdp->what)))
+	if (do_replace && entry_get_text_length(GTK_ENTRY(frdp->what)) > 0)
 	    gtk_widget_grab_focus(frdp->with);
 
-
 	vim_free(entry_text);
 	return;
     }
```
However, since I have no access to 2.10.4, I have to ask someone to see if it compiles with 2.10.4 and fixes #2563 as well.

**Comment by mcepl** [comment]
I would say that building for RHEL-5 is just an high-adrenaline sport not much more use of it. RHEL-5 is now in the state of deep freeze, and I really wonder whether having the latest-bleeding-edge version of vim has much value. If your employer insists on using RHEL-5 as a workstation machine, well, I don't know.

**Comment by brammool** [comment]
Kazunobu Kuriyama wrote:

> Hmm, according to the build log, the target GTK+ 2 is 2.10.4, which
> was released on 2007-07-16.  In general, as the current version is
> 2.24.31, it's too old to guarantee that the latest gvim having new
> features and bug fixes works well with it.
> 
> The current code around `gui_gtk.c:2201` should work with GTK+ >= 2.14.  To support GTK+ 2 older than that, the following patch could fix the issue:
> ```diff
> diff --git a/src/gui_gtk.c b/src/gui_gtk.c
> index c1b047974..b4433efd2 100644
> --- a/src/gui_gtk.c
> +++ b/src/gui_gtk.c
> @@ -2144,6 +2144,21 @@ convert_localized_message(char_u **buffer, const char *message)
>      return (const char *)*buffer;
>  }
>  
> +    static long
> +entry_get_text_length(GtkEntry *entry)
> +{
> +    g_return_val_if_fail(entry != NULL, 0);
> +    g_return_val_if_fail(GTK_IS_ENTRY(entry) == TRUE, 0);
> +
> +#if GTK_CHECK_VERSION(2,18,0)
> +    return gtk_entry_buffer_get_length(gtk_entry_get_buffer(entry));

Why add this 2.18 specific solution?  gtk_entry_get_text_length(),
available since 2.14, should work for 1.28 as well.

> +#elif GTK_CHECK_VERSION(2,14,0)
> +    return gtk_entry_get_text_length(entry);
> +#else
> +    return g_utf8_strlen(gtk_entry_get_text(entry), -1);
> +#endif
> +}
> +
>      static void
>  find_replace_dialog_create(char_u *arg, int do_replace)
>  {
> @@ -2198,10 +2213,9 @@ find_replace_dialog_create(char_u *arg, int do_replace)
>  	 * For :promptrepl dialog, give it to 'with' entry if 'what' has an
>  	 * non-empty entry; otherwise, to 'what' entry. */
>  	gtk_widget_grab_focus(frdp->what);
> -	if (do_replace && gtk_entry_get_text_length(GTK_ENTRY(frdp->what)))
> +	if (do_replace && entry_get_text_length(GTK_ENTRY(frdp->what)) > 0)
>  	    gtk_widget_grab_focus(frdp->with);
>  
> -
>  	vim_free(entry_text);
>  	return;
>      }
> ```
> However, since I have no access to 2.10.4, I have to ask someone to
> see if it compiles with 2.10.4 and fixes #2563 as well.

-- 
Microsoft's definition of a boolean: TRUE, FALSE, MAYBE
"Embrace and extend"...?

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by fusion809** [comment]
Sorry for the lateness of the reply. I am not using RHEL 5, I'm packaging for it and a large number of other distros in case someone wants to use them. My other build targets are working fine (and yes openSUSE Leap 42.3 is one of them). Trying out the patch atm.

**Comment by fusion809** [comment]
It worked. Thanks @nuko8!

**Comment by nuko8** [comment]
@brammool 

> Why add this 2.18 specific solution?  gtk_entry_get_text_length(), available since 2.14, should work for 1.28 as well.

That's due to my misinterpretation of what is written in [the manual on `gtk_entry_get_text_length()`](https://developer.gnome.org/gtk2/2.24/GtkEntry.html#gtk-entry-get-text-length) and needs an explanation.

When I read it at the first time, I thought
```
guint16
gtk_entry_get_text_length (GtkEntry *entry);

...

This is equivalent to:
gtk_entry_buffer_get_length (gtk_entry_get_buffer (entry));
```
meant something about the API for the versions < 2.14.  My previous patch is based on this misinterpretation, and thus it doesn't have the 2.18 specific solution.

But when I looked into the issue and reread the manual, I found I was wrong; it actually tells us about the API for the versions >= 2.18.  I hadn't noticed that until I clicked the `get_entry_get_buffer` link and found the function was introduced with 2.18.

As the function names indicate, GtkEntry changed its text data implementation from a raw byte string to a buffer object.  Although the current code works fine with GTK+ 2.14 and newer versions, the implementation change suggests us to get ready for the day when the API prior to 2.18 is declared "deprecated".  The addition is for making the patch a bit future-proof.

Oops, I found I chose a wrong return value type for the new function `entry_get_text_length()`.  Let me fix it:
```diff
diff --git a/src/gui_gtk.c b/src/gui_gtk.c
index c1b047974..fd0282bda 100644
--- a/src/gui_gtk.c
+++ b/src/gui_gtk.c
@@ -2144,6 +2144,21 @@ convert_localized_message(char_u **buffer, const char *message)
     return (const char *)*buffer;
 }
 
+    static unsigned long
+entry_get_text_length(GtkEntry *entry)
+{
+    g_return_val_if_fail(entry != NULL, 0);
+    g_return_val_if_fail(GTK_IS_ENTRY(entry) == TRUE, 0);
+
+#if GTK_CHECK_VERSION(2,18,0)
+    return gtk_entry_buffer_get_length(gtk_entry_get_buffer(entry));
+#elif GTK_CHECK_VERSION(2,14,0)
+    return gtk_entry_get_text_length(entry);
+#else
+    return g_utf8_strlen(gtk_entry_get_text(entry), -1);
+#endif
+}
+
     static void
 find_replace_dialog_create(char_u *arg, int do_replace)
 {
@@ -2198,10 +2213,9 @@ find_replace_dialog_create(char_u *arg, int do_replace)
 	 * For :promptrepl dialog, give it to 'with' entry if 'what' has an
 	 * non-empty entry; otherwise, to 'what' entry. */
 	gtk_widget_grab_focus(frdp->what);
-	if (do_replace && gtk_entry_get_text_length(GTK_ENTRY(frdp->what)))
+	if (do_replace && entry_get_text_length(GTK_ENTRY(frdp->what)) > 0)
 	    gtk_widget_grab_focus(frdp->with);
 
-
 	vim_free(entry_text);
 	return;
     }
```


@fusion809 

Thank you for taking your time for that!

**Comment by brammool** [comment]
Kazunobu Kuriyama wrote:

> @brammool 
> 
> > Why add this 2.18 specific solution?  gtk_entry_get_text_length(), available since 2.14, should work for 1.28 as well.
> 
> That's due to my misinterpretation of what is written in [the manual on `gtk_entry_get_text_length()`](https://developer.gnome.org/gtk2/2.24/GtkEntry.html#gtk-entry-get-text-length) and needs an explanation.
> 
> When I read it at the first time, I thought
> ```
> guint16
> gtk_entry_get_text_length (GtkEntry *entry);
> 
> ...
> 
> This is equivalent to:
> gtk_entry_buffer_get_length (gtk_entry_get_buffer (entry));
> ```
> meant something about the API for the versions < 2.14.  My previous patch is based on this misinterpretation, and thus it doesn't have the 2.18 specific solution.
> 
> But when I looked into the issue and reread the manual, I found I was wrong; it actually tells us about the API for the versions >= 2.18.  I hadn't noticed that until I clicked the `get_entry_get_buffer` link and found the function was introduced with 2.18.
> 
> As the function names indicate, GtkEntry changed its text data implementation from a raw byte string to a buffer object.  Although the current code works fine with GTK+ 2.14 and newer versions, the implementation change suggests us to get ready for the day when the API prior to 2.18 is declared "deprecated".  The addition is for making the patch a bit future-proof.
> 
> Oops, I found I chose a wrong return value type for the new function `entry_get_text_length()`.  Let me fix it:

Can you please add a few comments about the three versions?  Esp. theone
for 2.18, since it's not obvious it does something else than the code
for 2.14.


-- 
DINGO: Wicked wicked Zoot ... she is a bad person and she must pay the
       penalty.  And here in Castle Anthrax, we have but one punishment
       ... you must tie her down on a bed ... and spank her.  Come!
GIRLS: A spanking!  A spanking!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nuko8** [comment]
> Can you please add a few comments about the three versions?  Esp. the one for 2.18, since it's not obvious it does something else than the code for 2.14.

Yes, here you are:
```diff
diff --git a/src/gui_gtk.c b/src/gui_gtk.c
index c1b047974..a5099a134 100644
--- a/src/gui_gtk.c
+++ b/src/gui_gtk.c
@@ -2144,6 +2144,36 @@ convert_localized_message(char_u **buffer, const char *message)
     return (const char *)*buffer;
 }
 
+
+/* Returns the number of characters in GtkEntry. */
+    static unsigned long
+entry_get_text_length(GtkEntry *entry)
+{
+    g_return_val_if_fail(entry != NULL, 0);
+    g_return_val_if_fail(GTK_IS_ENTRY(entry) == TRUE, 0);
+
+#if GTK_CHECK_VERSION(2,18,0)
+    /* 2.18 introduced a new object GtkEntryBuffer to handle text data for
+     * GtkEntry instead of letting each instance of the latter have its own
+     * storage for that.  The code below is almost identical to the
+     * implementation of gtk_entry_get_text_length() for the versions >= 2.18.
+     */
+    return gtk_entry_buffer_get_length(gtk_entry_get_buffer(entry));
+#elif GTK_CHECK_VERSION(2,14,0)
+    /* 2.14 introduced a new function to avoid making memory management bugs
+     * which can happen when gtk_entry_get_text() is used without due care and
+     * attention. */
+    return gtk_entry_get_text_length(entry);
+#else
+    /* gtk_entry_get_text() returns the pointer to the storage allocated
+     * internally by the widget.  Accordingly, use the one with great care:
+     * Don't free it nor modify the contents it points to; call the function
+     * every time you need the pointer since its value may have been changed
+     * by the widget. */
+    return g_utf8_strlen(gtk_entry_get_text(entry), -1);
+#endif
+}
+
     static void
 find_replace_dialog_create(char_u *arg, int do_replace)
 {
@@ -2198,10 +2228,9 @@ find_replace_dialog_create(char_u *arg, int do_replace)
 	 * For :promptrepl dialog, give it to 'with' entry if 'what' has an
 	 * non-empty entry; otherwise, to 'what' entry. */
 	gtk_widget_grab_focus(frdp->what);
-	if (do_replace && gtk_entry_get_text_length(GTK_ENTRY(frdp->what)))
+	if (do_replace && entry_get_text_length(GTK_ENTRY(frdp->what)) > 0)
 	    gtk_widget_grab_focus(frdp->with);
 
-
 	vim_free(entry_text);
 	return;
     }
```
In case I miss the point, please let me know.
