### ISSUE TITLE
Vim build fails due to Perl 5.22.2 specific errors on Arch Linux

### ISSUE THREAD

**Issue by fusion809** [vim/vim#790]
Hi,

The Vim GTK+ 2 / GTK+ 3 interface is failing to build, on Arch Linux 64-bit and the error seems related to Perl. Here is the error message I am getting during the build of Vim GTK+ 2:

``` bash
tune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/gui_beval.o gui_beval.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -DDYNAMIC_LUA_DLL=\"liblua.so.5.3.2\" -I/usr/include -o objects/if_lua.o if_lua.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -DDYNAMIC_PERL_DLL=\"libperl.so\"  -D_REENTRANT -D_GNU_SOURCE -fwrapv  -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -I/usr/lib/perl5/core_perl/CORE  -o objects/if_perl.o auto/if_perl.c
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from if_perl.xs:610:0:
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_av_top_index’:
/usr/lib/perl5/core_perl/CORE/inline.h:20:5: error: ‘PERL_ARGS_ASSERT_AV_TOP_INDEX’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_AV_TOP_INDEX;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h:20:5: note: each undeclared identifier is reported only once for each function it appears in
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_append_utf8_from_native_byte’:
/usr/lib/perl5/core_perl/CORE/inline.h:242:5: error: ‘PERL_ARGS_ASSERT_APPEND_UTF8_FROM_NATIVE_BYTE’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_APPEND_UTF8_FROM_NATIVE_BYTE;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S__is_utf8_char_slow’:
/usr/lib/perl5/core_perl/CORE/inline.h:274:5: error: ‘PERL_ARGS_ASSERT__IS_UTF8_CHAR_SLOW’ undeclared (first use in this function)
     PERL_ARGS_ASSERT__IS_UTF8_CHAR_SLOW;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_is_safe_syscall’:
/usr/lib/perl5/core_perl/CORE/inline.h:305:5: error: ‘PERL_ARGS_ASSERT_IS_SAFE_SYSCALL’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_IS_SAFE_SYSCALL;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_sv_only_taint_gmagic’:
/usr/lib/perl5/core_perl/CORE/inline.h:390:5: error: ‘PERL_ARGS_ASSERT_SV_ONLY_TAINT_GMAGIC’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_SV_ONLY_TAINT_GMAGIC;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:2859: recipe for target 'objects/if_perl.o' failed
make[1]: *** [objects/if_perl.o] Error 1
make[1]: Leaving directory '/home/fusion809/GitHub/mine/PKGBUILDs/gvim-git/src/vim/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2
```

while the error message while building the GTK+ 3 interface is:

``` bash
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/gui_gtk_f.o gui_gtk_f.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -o objects/gui_beval.o gui_beval.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -DDYNAMIC_LUA_DLL=\"liblua.so.5.3.2\" -I/usr/include -o objects/if_lua.o if_lua.c
gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       -DDYNAMIC_PERL_DLL=\"libperl.so\"  -D_REENTRANT -D_GNU_SOURCE -fwrapv  -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2  -I/usr/lib/perl5/core_perl/CORE  -o objects/if_perl.o auto/if_perl.c
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from if_perl.xs:610:0:
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_av_top_index’:
/usr/lib/perl5/core_perl/CORE/inline.h:20:5: error: ‘PERL_ARGS_ASSERT_AV_TOP_INDEX’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_AV_TOP_INDEX;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h:20:5: note: each undeclared identifier is reported only once for each function it appears in
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_append_utf8_from_native_byte’:
/usr/lib/perl5/core_perl/CORE/inline.h:242:5: error: ‘PERL_ARGS_ASSERT_APPEND_UTF8_FROM_NATIVE_BYTE’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_APPEND_UTF8_FROM_NATIVE_BYTE;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S__is_utf8_char_slow’:
/usr/lib/perl5/core_perl/CORE/inline.h:274:5: error: ‘PERL_ARGS_ASSERT__IS_UTF8_CHAR_SLOW’ undeclared (first use in this function)
     PERL_ARGS_ASSERT__IS_UTF8_CHAR_SLOW;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_is_safe_syscall’:
/usr/lib/perl5/core_perl/CORE/inline.h:305:5: error: ‘PERL_ARGS_ASSERT_IS_SAFE_SYSCALL’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_IS_SAFE_SYSCALL;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/perl5/core_perl/CORE/inline.h: In function ‘S_sv_only_taint_gmagic’:
/usr/lib/perl5/core_perl/CORE/inline.h:390:5: error: ‘PERL_ARGS_ASSERT_SV_ONLY_TAINT_GMAGIC’ undeclared (first use in this function)
     PERL_ARGS_ASSERT_SV_ONLY_TAINT_GMAGIC;
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:2859: recipe for target 'objects/if_perl.o' failed
make[1]: *** [objects/if_perl.o] Error 1
make[1]: Leaving directory '/home/fusion809/GitHub/mine/PKGBUILDs/gvim-gtk3/src/vim-7.4.1825/src'
Makefile:26: recipe for target 'first' failed
make: *** [first] Error 2
```

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Aha this error disappeared when I downgraded Perl from 5.22.2 to 5.22.1.

**Comment by vim-ml** [comment]
Hello,

It looks from the error message that the issue is not relevant to any GTK+
stuff but to the if_perl module.

Also, please note that our build system is supposed to exclude
"-D_FORTIFY_SOURCE=2" or similar stuff by replacing it with
"-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1" for gcc >= 3.0 (cf. src/
configure.in:4275).

So I'm wondering why we have (an excerpt of the 3rd gcc command line):

gcc -c <snip> -D_FORTIFY_SOURCE=2 <snip> -U_FORTIFY_SOURCE
-D_FORTIFY_SOURCE=1 <snip> -D_FORTIFY_SOURCE=2 <snip> -o objects/if_perl.o
auto/if_perl.c

which looks to me as if the configure script was invoked with a command
line like

$ CPPFLAGS='-D_FORTIFY_SOURCES=2' ./configure

Hence it would be more helpful if you could tell us more about your build
configuration when you got the error. In particular, I have an interest in
a reason why "-D_FORTIFY_SOURCES=2"s were not filtered automatically by the
configure script and remained in the command lines to compile the if_lua
and if_perl modules.

Best regards,
Kazunobu Kuriyama

2016-05-09 10:16 GMT+09:00 Brenton Horne vim-dev-github@256bit.org:

**Comment by fusion809** [comment]
@vim-ml I'm afraid I don't know how to get the configuration settings you're referring to (I'm more an end-user than a developer) so I'll give you the best I can think of, the configure and make command used by my `gvim` PKGBUILD:

``` bash
    ./configure \
      --enable-fail-if-missing \
      --with-compiledby='Arch Linux AUR' \
      --prefix=/usr \
      --enable-gui=gtk2 \
      --with-features=huge \
      --enable-cscope \
      --enable-multibyte \
      --enable-perlinterp=dynamic \
      --enable-pythoninterp=dynamic \
      --enable-python3interp=dynamic \
      --enable-rubyinterp=dynamic \
      --enable-luainterp=dynamic
    make
```

**Comment by vim-ml** [comment]
Hmm...

I replied via vim_dev, got a spam in return, and visited GitHub to make
sure my message was sent.

Now I'm stunned at the fact that the title was changed, the contents was
changed, and there was a message which was not delivered to my mailbox.

What the hell social coding (lol)

2016-05-09 13:06 GMT+09:00 Brenton Horne vim-dev-github@256bit.org:

**Comment by pmattern** [comment]
The Arch Linux Build system (ABS) is setting make variable 'CPPFLAGS="-D_FORTIFY_SOURCE=2"' as well as some of the other flags seen above by default in its configuration file `/etc/makepkg.conf`.
These settings don't seem to be involved in the problem discussed here, though.

Rather, it seems to be an incompatibility between Perl 5.22_.2_ and value `dynamic` of configure option `--enable-perlinterp` as suggested by the following tests running `./configure` and `make` on up to date Arch Linux independently from its build system. In particular `CPPFLAGS="-D_FORTIFY_SOURCE` had been set to its expected value by the configure script ("checking whether we need -D_FORTIFY_SOURCE=1... yes"):
1. `./configure --enable-gui=no --enable-perlinterp=yes`: `make` runs flawlessly, no apparent issues in the code generated that way
2. `./configure --enable-gui=no --enable-perlinterp=dynamic`: `make` fails with error messages as posted above
3. Downgrade Perl to 5.22_.1_, `./configure --enable-gui=no --enable-perlinterp=dynamic`: same as 1.

**Comment by nuko8** [comment]
@pmattern 

Thank you for the feedback.  Now I understand where the D flag comes from.

Currently, we have [a patch](https://framagit.org/Damien43/patches/raw/master/vim/perl-5.22.2.patch) for fixing the issue, but unfortunately, it has been kept under review for a week.

This is because Bram and Damien, the author of the patch, are concerned about whether or not the patch breaks the Perl interface on older versions of Perl, say 5.18 (https://groups.google.com/forum/#!topic/vim_dev/xLXIFC8p3EY).

I think vim_dev would appreciate it if someone could have a try at the patch with an older Perl other than 5.22 and let us know the result here.

**Comment by hoelzro** [comment]
I just tried the patch on the following perls:
- 5.8.9
- 5.10.1
- 5.12.5

Each of them built ok, but when I ran vim and tried `:perl print 'hi'`, I got the following error:

```
E448: Could not load library function Perl_ISv_ptr                                             
Sorry, this command is disabled: the Perl library could not be loaded.
```

I'll try more recent perls later.

**Comment by hoelzro** [comment]
Alright, I tried the following versions as well:
- 5.14.4
- 5.16.3
- 5.18.4
- 5.20.3
- 5.22.2
- 5.24.0

For each of these versions, vim built correctly, and `:perl print 'hi'` works just fine.

**Comment by fusion809** [comment]
Well I just tried building gVim on the Open Build Service (OBS) and this Perl issue has reared its ugly head again https://build.opensuse.org/package/live_build_log/home:fusion809:arch_extra:extra/gvim/Arch_Extra/i586.

**Comment by pmattern** [comment]
@fusion809 
Did you apply the patch mentioned earlier? Otherwise the failure comes as no surprise.

Also, could you eventually exchange this issue's title with something less specific? Problem is not limited to gVim / GTK but affects Perl 5.22.2 in general.

**Comment by fusion809** [comment]
Oops didn't see the mention of a patch until now.

**Comment by k-takata** [comment]
@hoelzro Thank you for testing with old versions.

> I just tried the patch on the following perls:
> -   5.8.9
> -   5.10.1
> -   5.12.5

Do these failures depend on Damien's patch? Do they work without the patch?

**Comment by k-takata** [comment]
I tried to compile Vim 7.4.1847 with ActivePerl 5.10.1 and without Damien's patch. It failed with the following error:

```
if_perl.obj : error LNK2001: unresolved external symbol _Perl_sv_2nv
```

The error is different from @hoelzro's case, but it seems that if_perl has been already broken for very old perl.

**Comment by tgc** [comment]
I built rpms of 7.4.1832 without Damien's patch for these perls:
5.8.5 (el4)
5.8.8 (el5)
5.10.1 (el6)
5.16.3 (el7)

The ':perl print "hi"' test works on all of them.

To build with perl < 5.8.7 a fix is needed since it lacks the PERLIO_FUNCS_\* defines but once that is fixed it works.
The patch I made can be found here:
http://jupiterrise.com/tmp/vim-7.4-old-perl-support.patch

With 7.4.1848 the build is broken for 5.8.8 and 5.8.5:
objects/if_perl.o: In function `newBUFrv':
/builddir/build/BUILD/vim-7.4.1848/src/if_perl.xs:823: undefined reference to`SvREFCNT_inc_void_NN'
objects/if_perl.o: In function `newWINrv':
/builddir/build/BUILD/vim-7.4.1848/src/if_perl.xs:807: undefined reference to`SvREFCNT_inc_void_NN'
collect2: ld returned 1 exit status

A simple define allows the build to complete:
#ifndef SvREFCNT_inc_void_NN
#define SvREFCNT_inc_void_NN SvREFCNT_inc
#endif

With the two fixes in place the perl print test works with 7.4.1848 on these perls:
5.8.5 (el4)
5.8.8 (el5)
5.10.1 (el6)
5.16.3 (el7)

I also tested with perl 5.8.0 (el3) but it fails miserably:
Attempt to free temp prematurely: SV 0x9426824 during global destruction.
Attempt to free temp prematurely: SV 0x9426dc4 during global destruction.
Attempt to free temp prematurely: SV 0x9481ee4 during global destruction.
Attempt to free temp prematurely: SV 0x93471ac during global destruction.
Attempt to free temp prematurely: SV 0x93471b8 during global destruction.
Attempt to free temp prematurely: SV 0x9344388 during global destruction.
Attempt to free temp prematurely: SV 0x9344448 during global destruction.
Attempt to free temp prematurely: SV 0x930a2d4 during global destruction.
Attempt to free temp prematurely: SV 0x9344358 during global destruction.
Attempt to free temp prematurely: SV 0x93471c4 during global destruction.
Scalars leaked: 11Vim: Double signal, exiting

Attempt to free unreferenced scalar during global destruction.
Attempt to free unreferenced scalar during global destruction.
Attempt to free unreferenced scalar during global destruction.
Attempt to free unreferenced scalar during global destruction.Segmentation fault

**Comment by chrisbra** [comment]
Well, if el3 means Red Hat Enterprise Linux 3 which seems to be from 2003 and supported until January 2014, and considering the fact, that nobody complained about it, I think we can ignore that perl 5.8.0 (released 2002) does not work anymore.

**Comment by tgc** [comment]
Yes el3 refers to RHEL3 and compatible like CentOS 3 which is what I use for testing.

Also what causes the immediate segfault is the new perlIO based output support other perl stuff seems to work.
E.g. something like ':perl VIM::Msg("hello")' works with perl 5.8.0 however once you exit the session vim still dies with a segfault.
This is a regression since it worked without segfaulting in 7.4.1411 which is the previous version I built.

**Comment by chrisbra** [comment]
I am closing, as this should be solved by cf190c6f017563de1bdbf85 and 6727bf861776cfbb

**Comment by k-takata** [comment]
> A simple define allows the build to complete:
> #ifndef SvREFCNT_inc_void_NN
> #define SvREFCNT_inc_void_NN SvREFCNT_inc
> #endif

This part is not included. Is it okay?

**Comment by brammool** [comment]
Ken Takata wrote:

> > A simple define allows the build to complete:
> > #ifndef SvREFCNT_inc_void_NN
> > #define SvREFCNT_inc_void_NN SvREFCNT_inc
> > #endif
> 
> This part is not included. Is it okay?

Must have missed this.  I'll include it.

## 

Have you heard about the new Beowulf cluster? It's so fast, it executes
an infinite loop in 6 seconds.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by vim-ml** [comment]
Hey friend, 

I thought this information  regarding my favourite stuff may be usefull for you too,  just take a  look  here <http://pin.vimconsole.com/e4veymai>


Hugs, paul

**Comment by vim-ml** [comment]
Hey friend, 

I've  got some news for you, please read  it, this really  matters a lot! Please read  here <http://first.fidemlogistcs.com/e4jgwj>

Typos courtesy of my iPhone, paul
