### ISSUE TITLE
`find_module` is deleted in python3.13

### ISSUE THREAD

**Issue by Ghost-LZW** [vim/vim#14776]
### Steps to reproduce

https://github.com/vim/vim/blob/master/src/if_py_both.h#L7328-L7333

since python3.13, `find_module` is deleted https://github.com/python/cpython/pull/98059

maybe we should just delete L7328-L7333

### Expected behaviour

work with python 3.13

### Version of Vim

9.1

### Environment

Python 3.13.0b1

### Logs and stack traces

```shell
`:python3 import vim; vim.find_module`


PathFinder has no attribute 'find_module'
```
```

**Comment by chrisbra** [comment]
I guess we should include this only within the following `#ifdef` then? 
```c
#if PY_VERSION_HEX < 0x30d00f0
    if ((py_find_module = PyObject_GetAttrString(cls, "find_module")))
    {
	// find_module() is deprecated, this may stop working in some later
	// version.
	ADD_OBJECT(m, "_find_module", py_find_module);
    }
#endif
```

This would only test for 3.13.0 release version, even so it has already been deleted in some 3.13 beta and alpha versions apparently

**Comment by welandx** [comment]
same error when using python3.13.3
no errors in python3.12.10

**Comment by chrisbra** [comment]
This functionality was removed inside Python and need to be fixed there then.
