### ISSUE TITLE
Vim won't build with Tcl 9.0.0 (yet)

### ISSUE THREAD

**Issue by dertuxmalwieder** [vim/vim#15769]
### Steps to reproduce

On Windows 10:

1. Download Tcl 9.0.0 and unzip/un-gzip the archive.
2. `cd <tcl>/win ; nmake -f Makefile.vc ; nmake -f Makefile.vc install`
3. Build Vim, pointing to the Tcl directory.
4. Find that `if_tcl.c`, working flawlessly with Tcl 8.6, just dies. Log below.

### Expected behaviour

It should just work.

### Version of Vim

9.1.0748

### Environment

Windows 10, Visual Studio 2022, 64-bit cmd.

### Logs and stack traces

```shell
(Complete if_tcl log:)

if_tcl.c(130): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(130): error C2059: Syntaxfehler: ";"
if_tcl.c(130): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(131): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(131): error C2059: Syntaxfehler: ";"
if_tcl.c(131): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(132): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(132): error C2059: Syntaxfehler: ";"
if_tcl.c(132): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(133): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(133): error C2059: Syntaxfehler: ";"
if_tcl.c(133): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(134): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(134): error C2059: Syntaxfehler: ";"
if_tcl.c(134): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(135): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(135): error C2059: Syntaxfehler: ";"
if_tcl.c(135): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(136): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(136): error C2059: Syntaxfehler: ";"
if_tcl.c(136): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(137): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(137): error C2059: Syntaxfehler: ";"
if_tcl.c(137): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(138): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(138): error C2059: Syntaxfehler: ";"
if_tcl.c(138): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(140): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(140): error C2059: Syntaxfehler: ";"
if_tcl.c(140): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(141): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(141): error C2059: Syntaxfehler: ";"
if_tcl.c(141): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(142): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(142): error C2059: Syntaxfehler: ";"
if_tcl.c(142): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(143): error C2061: Syntaxfehler: Bezeichner "_ANSI_ARGS_"
if_tcl.c(143): error C2059: Syntaxfehler: ";"
if_tcl.c(143): error C2059: Syntaxfehler: "<parameter-list>"
if_tcl.c(407): warning C4013: "tclgetbuffer" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(407): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(433): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(489): warning C4013: "tclgetwindow" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(489): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(550): warning C4013: "tclfindwin" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(550): warning C4047: "=": Anzahl der Dereferenzierungen bei "win_T *" und "int" unterschiedlich
if_tcl.c(557): warning C4013: "tcldoexcommand" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(562): warning C4013: "tclsetoption" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(567): warning C4013: "tclvimexpr" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(631): warning C4013: "tclgetlinenum" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(807): warning C4013: "vimerror" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(902): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(925): warning C4013: "tclsetdelcmd" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(1037): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(1223): error C2040: "tclfindwin": "win_T *(buf_T *)" unterscheidet sich von "int ()" in Bezug auf die Anzahl vorgenommener Dereferenzierungen
if_tcl.c(1286): warning C4013: "tcldelthisinterp" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(1288): warning C4013: "tclupdatevars" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(1518): error C2040: "tclgetwindow": "char *(Tcl_Interp *,win_T *)" unterscheidet sich von "int ()" in Bezug auf die Anzahl vorgenommener Dereferenzierungen
if_tcl.c(1524): error C2040: "tclgetbuffer": "char *(Tcl_Interp *,buf_T *)" unterscheidet sich von "int ()" in Bezug auf die Anzahl vorgenommener Dereferenzierungen
if_tcl.c(1620): warning C4013: "tclmsg" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(1623): warning C4013: "tclerrmsg" undefiniert; Annahme: extern mit Rückgabetyp int
if_tcl.c(1655): error C2065: "TCL_CHANNEL_VERSION_2": nichtdeklarierter Bezeichner
if_tcl.c(1652): error C2099: Initialisierung ist keine Konstante
if_tcl.c(1656): warning C4047: "Initialisierung": Anzahl der Dereferenzierungen bei "Tcl_ChannelTypeVersion" und "int (__cdecl *)(ClientData,Tcl_Interp *)" unterschiedlich
if_tcl.c(1662): warning C4113: "void (__cdecl *)(ClientData,int)" weicht in der Parameterliste von "Tcl_DriverGetOptionProc (__cdecl *)" ab
if_tcl.c(1662): warning C4133: "Initialisierung": Inkompatible Typen - von "void (__cdecl *)(ClientData,int)" zu "Tcl_DriverGetOptionProc (__cdecl *)"
if_tcl.c(1663): warning C4113: "int (__cdecl *)(ClientData,int,ClientData *)" weicht in der Parameterliste von "Tcl_DriverWatchProc (__cdecl *)" ab
if_tcl.c(1688): error C2371: "tclupdatevars": Neudefinition; unterschiedliche Basistypen
if_tcl.c(1703): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(1708): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(1801): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(1805): warning C4047: "=": Anzahl der Dereferenzierungen bei "char *" und "int" unterschiedlich
if_tcl.c(1825): error C2371: "tclerrmsg": Neudefinition; unterschiedliche Basistypen
if_tcl.c(1840): error C2371: "tclmsg": Neudefinition; unterschiedliche Basistypen
if_tcl.c(1855): error C2371: "tcldelthisinterp": Neudefinition; unterschiedliche Basistypen
```

**Comment by dertuxmalwieder** [comment]
Relevant Tcl wiki: [Porting extensions to Tcl 9](https://wiki.tcl-lang.org/page/Porting+extensions+to+Tcl+9).
