### PR TITLE
After 9.1.1637: Fix build failure if FEAT_DIFF is not defined

### PR DESCRIPTION
**Pull request by basilisk0315**
After patch 9.1.1637, my Windows x64 build using clang 20.1.8 fails if FEAT_DIFF is not defined:
`clang -c -I. -Iproto -DWIN32 -DWINVER=0x0A00 -D_WIN32_WINNT=0x0A00 -DHAVE_PATHDEF -DFEAT_NORMAL -DHAVE_STDINT_H -D__USE_MINGW_ANSI_STDIO -pipe -Wall -O3 -fomit-frame-pointer -fpie -fPIE -Db_lto=true -Db_lto_mode=thin -march=native -DFEAT_GUI_MSWIN -DFEAT_CLIPBOARD evalfunc.c -o gobjx86-64/evalfunc.o`
`evalfunc.c:2140:14: error: use of undeclared identifier 'f_diff'; did you mean 'fdimf'?`
` 2140 |                         ret_any,  f_diff},`
`      |                                   ^~~~~~`
`      |                                   fdimf`
`E:/msys64/ucrt64/include/math.h:950:24: note: 'fdimf' declared here`
`  950 |   extern float __cdecl fdimf (float x, float y);`
`      |                        ^`
`evalfunc.c:2142:20: error: use of undeclared identifier 'f_diff_filler'`
` 2142 |                         ret_number,         f_diff_filler},`
`      |                                             ^`
`evalfunc.c:2144:20: error: use of undeclared identifier 'f_diff_hlID'`
` 2144 |                         ret_number,         f_diff_hlID},`
`      |                                             ^`
`evalfunc.c:3215:25: error: invalid application of 'sizeof' to an incomplete type 'funcentry_T[]'`
` 3215 |     if (++intidx < (int)ARRAY_LENGTH(global_functions))`
`      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`./macros.h:436:32: note: expanded from macro 'ARRAY_LENGTH'`
`  436 | #define ARRAY_LENGTH(a) (sizeof(a) / sizeof((a)[0]))`
`      |                                ^~~`
`evalfunc.c:3265:17: error: invalid application of 'sizeof' to an incomplete type 'funcentry_T[]'`
` 3265 |     last = (int)ARRAY_LENGTH(global_functions) - 1;`
`      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`./macros.h:436:32: note: expanded from macro 'ARRAY_LENGTH'`
`  436 | #define ARRAY_LENGTH(a) (sizeof(a) / sizeof((a)[0]))`
`      |                                ^~~`
`5 errors generated.`
`make: *** [Make_cyg_ming.mak:1274: gobjx86-64/evalfunc.o] Error 1`

Cheers
John

### CODE REVIEW

**Comment by chrisbra** [comment]
That doesn't look right. Those functions are defined independently of whether `FEAT_DIFF` exists or not, although in that case it's just an empty function body. So how about this patch instead:
```diff
diff --git a/src/proto.h b/src/proto.h
index 3c34fe813..e9e5efcbc 100644
--- a/src/proto.h
+++ b/src/proto.h
@@ -73,9 +73,7 @@ extern int _stricoll(char *a, char *b);
 # include "if_cscope.pro"
 # include "debugger.pro"
 # include "dict.pro"
-# ifdef FEAT_DIFF
 # include "diff.pro"
-# endif
 # include "linematch.pro"
 # include "digraph.pro"
 # include "drawline.pro"
diff --git a/src/structs.h b/src/structs.h
index d7b458077..eecb6b2ef 100644
--- a/src/structs.h
+++ b/src/structs.h
@@ -3671,6 +3671,9 @@ struct diffline_S
     int bufidx;
     int lineoff;
 };
+#else // FEAT_DIFF
+typedef void diffline_change_T;
+typedef void diffline_T;
 #endif

 #define SNAP_HELP_IDX  0
```

**Comment by basilisk0315** [comment]
> That doesn't look right. Those functions are defined independently of whether `FEAT_DIFF` exists or not, although in that case it's just an empty function body. So how about this patch instead:
> 
> ```diff
> diff --git a/src/proto.h b/src/proto.h
> index 3c34fe813..e9e5efcbc 100644
> --- a/src/proto.h
> +++ b/src/proto.h
> @@ -73,9 +73,7 @@ extern int _stricoll(char *a, char *b);
>  # include "if_cscope.pro"
>  # include "debugger.pro"
>  # include "dict.pro"
> -# ifdef FEAT_DIFF
>  # include "diff.pro"
> -# endif
>  # include "linematch.pro"
>  # include "digraph.pro"
>  # include "drawline.pro"
> diff --git a/src/structs.h b/src/structs.h
> index d7b458077..eecb6b2ef 100644
> --- a/src/structs.h
> +++ b/src/structs.h
> @@ -3671,6 +3671,9 @@ struct diffline_S
>      int bufidx;
>      int lineoff;
>  };
> +#else // FEAT_DIFF
> +typedef void diffline_change_T;
> +typedef void diffline_T;
>  #endif
> 
>  #define SNAP_HELP_IDX  0
> ```

Yes this looks like a better solution.

**Comment by chrisbra** [comment]
I opened #18046 for this
