### ISSUE TITLE
vim not build with upcoming Perl 5.38

### ISSUE THREAD

**Issue by jplesnik** [vim/vim#12543]
### Steps to reproduce

I am preparing update to Perl 5.38 for Fedora 39. During the preparation I tried to rebuild all dependencies with it.
I found that build of vim was failing with new Perl.
For the tests I used the latest devel release [Perl 5.37.11](https://cpan.metacpan.org/authors/id/S/SH/SHAY/perl-5.37.11.tar.gz) 

### Expected behaviour

Successful build of vim

### Version of Vim

9.0 1627

### Environment

Fedora 39 (rawhide)
Devel release of Perl  5.37.11

### Logs and stack traces

```shell
Complete log coulg be found on <https://jplesnik.fedorapeople.org/5.38/vim-build.log>
Examples from log: 

if_perl.xs: In function 'Perl_SvTRUE_common': 
/usr/lib64/perl5/CORE/embed.h:109:49: warning: implicit declaration of function 'Perl_SvPVXtrue'; did you mean 'Perl_sv_true'? [-Wimplicit-function-declaration]
  109 | # define SvPVXtrue(a)                           Perl_SvPVXtrue(aTHX_ a)
      |                                                 ^~~~~~~~~~~~~~
if_perl.xs:724:16: note: in expansion of macro 'SvPVXtrue'
  724 |         return SvPVXtrue(sv);
      |                ^~~~~~~~~
if_perl.xs: In function 'Perl_SvTRUE':
<...>
/usr/bin/ld: /tmp/ccxXLZZi.ltrans63.ltrans.o: in function `ex_perl':
/builddir/build/BUILD/vim90/src/if_perl.xs:745: undefined reference to `Perl_SvGETMAGIC'
/usr/bin/ld: /builddir/build/BUILD/vim90/src/if_perl.xs:1108: undefined reference to `Perl_SvPV_helper'
/usr/bin/ld: /builddir/build/BUILD/vim90/src/if_perl.xs:724: undefined reference to `Perl_SvPVXtrue'
/usr/bin/ld: /tmp/ccxXLZZi.ltrans63.ltrans.o: in function `perl_to_vim.lto_priv.0':
/builddir/build/BUILD/vim90/src/if_perl.xs:1210: undefined reference to `Perl_SvPV_helper'
/usr/bin/ld: /builddir/build/BUILD/vim90/src/if_perl.xs:1323: undefined reference to `Perl_SvPV_helper'
/usr/bin/ld: /builddir/build/BUILD/vim90/src/if_perl.xs:1199: undefined reference to `Perl_SvNV'
/usr/bin/ld: /builddir/build/BUILD/vim90/src/if_perl.xs:1203: undefined reference to `Perl_SvIV'
/usr/bin/ld: /tmp/ccxXLZZi.ltrans64.ltrans.o: in function `XS_VIM_DoCommand':
/builddir/build/BUILD/vim90/src/if_perl.c:1789: undefined reference to `Perl_SvPV_helper'
/usr/bin/ld: /tmp/ccxXLZZi.ltrans64.ltrans.o: in function `ex_perldo':
/builddir/build/BUILD/vim90/src/if_perl.xs:1433: undefined reference to `Perl_SvPV_helper'

```

**Comment by zdohnal** [comment]
> A potential workaround is to configure with `--enable-perlinterp=dynamic` 

That's how Vim is built in Fedora. However, once in time the languages define new functions in newer release, which Vim has to fake it to make this dynamic linking working - the same thing happens time to time with Python and Ruby as well.

**Comment by zdohnal** [comment]
How to reproduce:

- configure+build+install Perl from the link in the first comment:

```
$ wget -O perl.tar.gz https://cpan.metacpan.org/authors/id/S/SH/SHAY/perl-5.37.11.tar.gz
$ tar -xaf perl.tar.gz && cd perl-5.37.11
$ <install make and gcc>
$ # sets the options interactively
$ sh Configure
$ make && sudo make install
``` 
- compile Vim with new Perl:

```
$ git clone https://github.com/vim/vim
$ cd vim
$ ./configure --enable-gui=no --with-features=Huge --enable-perlinterp=dynamic
$ make
```

**Comment by pheiduck** [comment]
Arch Linux has Perl 5.36.1, seems like it is no longer possible to build vim with perl starting with 5.37.

**Comment by pheiduck** [comment]
I'm not a programer and know much about perl but could this be a patch for that issue?:
```
/* perl-5.37 needs Perl_sv_true */
# if (PERL_REVISION == 5) && (PERL_VERSION >= 37)
# define sv_true(a) Perl_sv_true(aTHX_ a)
# endif
```

**Comment by pheiduck** [comment]
I build it with my patch but there are more bugs so I am not able to fix it, maybe someone else can do it.

**Comment by pheiduck** [comment]
But here are the Links where I found the code which is missing:
Not all
'Perl_sv_true'
https://github.com/Perl/perl5/blob/blead/embed.h
`Perl_SvPV_helper'
https://github.com/Perl/perl5/blob/blead/sv.h

**Comment by pheiduck** [comment]
another potential "fixup":
```diff
diff --git a/src/if_perl.xs b/src/if_perl.xs
index c69ed9ef1..00e296882 100644
--- a/src/if_perl.xs
+++ b/src/if_perl.xs
@@ -10,6 +10,11 @@
  *             Mostly written by Sven Verdoolaege.
  */

+#if (PERL_REVISION == 5) && (PERL_VERSION >= 37)
+#pragma GCC diagnostic ignored "-Wimplicit-function-declaration"
+CFLAGS="-Wl,--unresolved-symbols=ignore-all"
+#endif
+
 #define _memory_h      /* avoid memset redeclaration */
 #define IN_PERL_FILE   /* don't include if_perl.pro from proto.h */
```

**Comment by pheiduck** [comment]
I have good news:
My Last PR fixes the errors mentioned here.
And I learned a lot about Perl today. 😄

**Comment by jplesnik** [comment]
@pheiduck  I tested your changes with Fedora 39 and Perl 5.38.0-RC2 and it works for me. 
Thank you
