### ISSUE TITLE
Support for ruby 1.8 broken since 8.1.1056

### ISSUE THREAD

**Issue by tgc** [vim/vim#4257]
Since 8.1.1056 builds with Ruby 1.8.x as shipped with RHEL 6 and older are failling:
if_ruby.c: In function 'convert_hash2dict':
if_ruby.c:1816: error: 'ST_STOP' undeclared (first use in this function)
if_ruby.c:1816: error: (Each undeclared identifier is reported only once
if_ruby.c:1816: error: for each function it appears in.)
if_ruby.c:1818: error: 'ST_CONTINUE' undeclared (first use in this function)
make: *** [objects/if_ruby.o] Error 1

I previously built 8.1.982 with no issues against ruby 1.8.1 (el4), 1.8.5 (el5) and 1.8.7 (el6).
RHEL 7 ships with Ruby 2.0.0 and is not affected.

I was able to fix the build with ruby 1.8.x by adding #include <st.h> to if_ruby.c.

**Comment by tonymec** [comment]
openSUSE 15.0 ships with Ruby 2.5.0p0 and is not affected either.

Maybe there is a missing `#ifdef` and/or a missing configure test somewhere?

**Comment by brammool** [comment]
Don't you mean including ruby/st.h ?

**Comment by brammool** [comment]
@ichizok introduced this in patch 8.1.1056

**Comment by ichizok** [comment]
In Ruby < 1.9.0, st.h is placed under include-dir directly. 

```diff
--- a/src/if_ruby.c
+++ b/src/if_ruby.c
@@ -118,6 +118,9 @@
 #ifdef RUBY19_OR_LATER
 # include <ruby/encoding.h>
 #endif
+#ifndef RUBY19_OR_LATER
+# include <st.h>
+#endif

 #undef off_t   /* ruby defines off_t as _int64, Mingw uses long */
 #undef EXTERN
```

**Comment by tgc** [comment]
> Don't you mean including ruby/st.h ?

No, for ruby 1.8.x it is just <st.h>. Later releases moved the includes to ruby/.
