### ISSUE TITLE
Regression: Build with Ruby interpreter fails with "undefined reference to __libc_csu_fini" (after 8.2.2104)

### ISSUE THREAD

**Issue by inkarkat** [vim/vim#7439]
**Describe the bug**
My nightly test run on an older 32-bit Linux machine suddenly fails to build Vim:

```
  gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed  -o vim objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/fold.o objects/getchar.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/list.o objects/locale.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/syntax.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9compile.o objects/vim9execute.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o objects/gui.o objects/gui_gtk.o objects/gui_gtk_x11.o objects/gui_gtk_f.o objects/gui_beval.o objects/gui_gtk_gresources.o objects/vterm_encoding.o objects/vterm_keyboard.o objects/vterm_mouse.o objects/vterm_parser.o objects/vterm_pen.o objects/vterm_screen.o objects/vterm_state.o objects/vterm_unicode.o objects/vterm_vterm.o       objects/if_ruby.o  objects/netbeans.o objects/job.o objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o  objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo  -lselinux -lcanberra -lacl -lattr -lgpm -ldl       -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm  -L/usr/lib    
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0xc): undefined reference to `__libc_csu_fini'
/usr/lib/gcc/i686-linux-gnu/5/../../../i386-linux-gnu/crt1.o: In function `_start':
(.text+0x11): undefined reference to `__libc_csu_init'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
Makefile:2132: recipe for target 'vim' failed
make[1]: *** [vim] Error 1
```

I've bisected the problem to this commit:

> Author: Bram Moolenaar <Bram@vim.org>
> Date:   2020-12-06 21:11:31 +0100
>
>     patch 8.2.2104: build problem with Ruby 2.7
>     
>     Problem:    Build problem with Ruby 2.7.
>     Solution:   Adjust function declarations. (Ozaki Kiichi, closes #7430)

My 64-bit system (same Ubuntu 16.04, same Ruby 2.3.1) builds just fine. Excluding the Ruby interpreter (`--enable-rubyinterp`) also avoids the problem.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run `./configure --with-features=huge --enable-fail-if-missing --enable-rubyinterp && make`

**Expected behavior**
Build should continue to work on supported platforms.

**Environment (please complete the following information):**
 - Vim version 8.2.2104
 - OS: Ubuntu 16.04.7, 32-bit only, Ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]

**Comment by inkarkat** [comment]
Here's the full [buildlog](https://github.com/vim/vim/files/5658178/buildlog_20201208-095147.txt).

**Comment by chrisbra** [comment]
ping @ichizok

**Comment by brammool** [comment]
Ingo Karkat wrote:

> **Describe the bug**
> My nightly test run on an older 32-bit Linux machine suddenly fails to
> build Vim:

Can you perhaps suggest a fix?  Since you can reproduce the problem, you
could try a different solution from that patch.  Rolling it back will
bring back the problem it fixed, hopefully we can fix both.


-- 
It is illegal for anyone to try and stop a child from playfully jumping over
puddles of water.
		[real standing law in California, United States of America]

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by inkarkat** [comment]
Bram wrote:
> Since you can reproduce the problem, you
> could try a different solution from that patch.  Rolling it back will
> bring back the problem it fixed, hopefully we can fix both.

The [actual warning fix](https://github.com/vim/vim/pull/7430/commits/bca60ef0a2a2dd3fe6c9d519d5f6875bb165b23f) still builds fine when included. It's the second commit that [fixes ruby linking on macOS](https://github.com/vim/vim/pull/7430/commits/64568a9fe40645eb28cb3fb731a36f836187fddb) that causes the problem. So maybe all that is needed is an additional condition for macOS there so that it doesn't apply to Linux.

I hope that allows @ichizok to provide a fix, as this autoconf stuff is over my head. I personally could live with just excluding the Ruby interpreter from my build as a workaround; I just thought I report this as it has a clear origin and happened only very recently.

**Comment by ichizok** [comment]
Hmm, I constructed the roughly same environment in my VM but cannot reproduce.

https://gist.github.com/ichizok/58874a88ba62fda5df6aeb55074afec0

**Comment by inkarkat** [comment]
@ichizok: Thank you for looking so quickly into this! In the meantime, I've also downloaded a Ubuntu 16.04 32-bit VM (from https://www.osboxes.org/), set up a build environment, and also was able to cleanly compile the latest Vim there. Strange.

As this is not reproducible on another system, let's close this then. I can live with disabling the Ruby integration, and probably will move off that old machine (and off its 32-bit operating system) soon, anyway.
