### PR TITLE
win32: Fix compilation error with Ruby 3.0

### PR DESCRIPTION
**Pull request by k-takata**
if_ruby couldn't compile with Ruby 3.0 on MS-Windows even after #7564 and #7638.

@ichizok and @zdohnal,
Could you check if this works on your environment?

### CODE REVIEW

**Comment by zdohnal** [comment]
Hi @k-takata,

the pull request works on all archs where Fedora is built. Thank you for the heads up!

**Comment by ichizok** [comment]
Build warning by gcc 9.3.0 on Ubuntu 20.04 (using Ruby 3.0.0):

```
if_ruby.c: In function ‘ruby_malloc_size_overflow_stub’:
if_ruby.c:624:1: warning: ‘noreturn’ function does return
  624 | }
      | ^
```

**Comment by zdohnal** [comment]
Ah, I didn't check the warnings... Fedora builds have the same warning as Ubuntu.

**Comment by k-takata** [comment]
Okay, how about this.
Using `NORETURN` to a variable causes C3829 error on MSVC ("standard attribute 'noreturn' may only be applied to functions").

**Comment by ichizok** [comment]
It's OK on my env.

**Comment by zdohnal** [comment]
No new warnings in Fedora neither and the build  passes.
