### ISSUE TITLE
Vim fails to build with Python 3.10 and --enable-python3interp=dynamic

### ISSUE THREAD

**Issue by zdohnal** [vim/vim#8356]
**Describe the bug**
Vim fails to build if Python 3.10.0b2 is installed and Vim is configured with --enable-python3interp=dynamic

**To Reproduce**
Detailed steps to reproduce the behavior:
1. ./configure --enable-python3interp=dynamic
2. make

```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccAtQvSb.ltrans62.ltrans.o: in function `ConvertFromPySequence.lto_priv.0':
<artificial>:(.text+0x67cc): undefined reference to `PyIter_Check'
/usr/bin/ld: /tmp/ccAtQvSb.ltrans62.ltrans.o: in function `_ConvertFromPyObject.part.0.lto_priv.0':
<artificial>:(.text+0x7b0a): undefined reference to `PyType_IsSubtype'
/usr/bin/ld: <artificial>:(.text+0x7b32): undefined reference to `PyIter_Check'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
make: *** [Makefile:2142: vim] Error 1
```

**Expected behavior**
Vim is successfully built.

**Environment (please complete the following information):**
 - Vim 8.2.2968
 - OS: Fedora 35 (rawhide)

I'm trying to come up with the patch, but no luck so far.
