### PR TITLE
[WIP] if_python3.c: Fixing linker errors when dynamic python3interp is used

### PR DESCRIPTION
**Pull request by zdohnal**
Hi,

this is basically follow-up of #4080 - 

How to reproduce (Fedora 32/33) (using patchlevel 1199):
```
$ ./configure --enable-python3interp=dynamic && make
```

Error(snippets):
```
/usr/bin/ld: objects/if_python3.o: in function `py3__Py_DECREF':
/usr/bin/ld: /builddir/build/BUILD/vim82/src/if_python3.c:617: undefined reference to `_Py_Dealloc'
/usr/bin/ld: objects/if_python3.o: in function `PyType_HasFeature':
/usr/include/python3.9/object.h:622: undefined reference to `PyType_GetFlags'
/usr/bin/ld: objects/if_python3.o: in function `BufferNew':
/builddir/build/BUILD/vim82/src/if_py_both.h:5175: undefined reference to `_PyObject_New'
```
and similar.

Py_DEBUG seems to turned off in Fedora. But if I turn it on in CFLAGS it results in a different linker errors:
```
/usr/bin/ld: objects/if_python3.o: in function `_Py_INCREF':
/usr/include/python3.9/object.h:406: undefined reference to `_Py_RefTotal'
/usr/bin/ld: objects/if_python3.o: in function `PyType_HasFeature':
/usr/include/python3.9/object.h:622: undefined reference to `PyType_GetFlags'
/usr/bin/ld: objects/if_python3.o: in function `Py3Init_vim':
/builddir/build/BUILD/vim82/src/if_python3.c:1604: undefined reference to `PyModule_Create2'
```

I chose to fix the linker errors by adding logical OR with ```if defined(Py_DEBUG)``` which will check python3 version - meaning ```if (defined(Py_DEBUG) || PY_VERSION_HEX >= 0x030800f0)``` for ```_Py_Dealloc``` and ```_PyObject_New```.
```PyType_HasFeature``` is completely new, so I added py3__PyType_HasFeature() function pointer when python >= 3.8.

I tested the build with python 3.7 (Fedora 31), 3.8 (Fedora 32) and 3.9 (Fedora 33), and all builds went well with the patch.

Note:
I'm sorry for reporting late, I thought I had it fixed in spec file, but the fix made dynamic python3 linking useless, because it statically built Vim with python3 libs. I was able to find this out thanks to @k-takata yesterday after reporting Vim linking error with Lua.

### CODE REVIEW

File: src/if_python3.c [hunk 1]
```diff
@@ -777,7 +792,7 @@ static int python_end_called = FALSE;
     static void
 call_PyObject_Free(void *p)
 {
-#if defined(Py_DEBUG) && !defined(Py_DEBUG_NO_PYMALLOC)
+# if (defined(Py_DEBUG) || PY_VERSION_HEX >= 0x030800f0) && !defined(Py_DEBUG_NO_PYMALLOC)
```
Comment (k-takata) [inline src/if_python3.c]:
```suggestion
#if (defined(Py_DEBUG) || PY_VERSION_HEX >= 0x030800f0) && !defined(Py_DEBUG_NO_PYMALLOC)
```

Comment (zdohnal) [reply src/if_python3.c]: Sorry, overlooked that - committing right away.

**Comment by zdohnal** [comment]
Squashed.

**Comment by brammool** [comment]
I'm getting errors with Python 3.8.2:
if_python3.c:207: warning: "PyType_HasFeature" redefined
  207 | #  define PyType_HasFeature py3_PyType_HasFeature
      | 
In file included from /usr/include/python3.8/object.h:746,
                 from /usr/include/python3.8/pytime.h:6,
                 from /usr/include/python3.8/Python.h:85,
                 from if_python3.c:69:
/usr/include/python3.8/cpython/object.h:337: note: this is the location of the previous definition
  337 | #define PyType_HasFeature(t,f)  (((t)->tp_flags & (f)) != 0)
      | 
if_python3.c:240: warning: "_Py_Dealloc" redefined
  240 | #  define _Py_Dealloc py3__Py_Dealloc
      | 
In file included from /usr/include/python3.8/object.h:746,
                 from /usr/include/python3.8/pytime.h:6,
                 from /usr/include/python3.8/Python.h:85,
                 from if_python3.c:69:
/usr/include/python3.8/cpython/object.h:349: note: this is the location of the previous definition
  349 | #define _Py_Dealloc(op) _Py_Dealloc_inline(op)
      |

**Comment by zdohnal** [comment]
@brammool what OS do you use? I would like to reproduce it. Are you using the same reproducer? (Fedora 32 has python 3.8.3)

**Comment by brammool** [comment]
> @brammool what OS do you use? I would like to reproduce it. Are you
> using the same reproducer?

Ubuntu 20.04.

-- 
"Space is big.  Really big.  You just won't believe how vastly hugely mind-
bogglingly big it is.  I mean, you may think it's a long way down the
road to the chemist, but that's just peanuts to space."
		-- Douglas Adams, "The Hitchhiker's Guide to the Galaxy"

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\\
\\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I tested this on Windows with Python 3.8, but it didn't work.
`PyType_HasFeature` is a macro defined in `cpython/object.h` in Python 3.8 and not an exported function. So, when executing the `:py3` command, Vim fails to load the `PyType_HasFeature` function.

@zdohnal It seems that you are using Python 3.9, shouldn't it be applied only for 3.9?
(I haven't tested 3.9, because it is not released yet.)

**Comment by k-takata** [comment]
I confirmed that the following patch works with Python 3.9.0b4 on Windows:
https://gist.github.com/k-takata/bc7dc379b51f57c9c810b8a3159adfab

Note that `PY_VERSION_HEX` is `0x030900b0` on Python 3.9.0b4 (because it is beta) and it will become `0x030900f0` when the final version is released. So, `#if PY_VERSION_HEX >= 0x030900f0` doesn't work for now. I use `0x03090000` in the above patch instead.

**Comment by zdohnal** [comment]
@brammool Thanks, I have 20.04 in VM, I'll check it.

@k-takata You're right, I tested it manually with Python 3.9, but then I ran the build for older Fedoras (meaning python3.8 and python3.7) and it was built fine...

Anyway, thank you for testing and proposed changes, I'll check the changes within Ubuntu and manually within older Fedoras.

**Comment by zdohnal** [comment]
@brammool I'm unable to reproduce the errors you got in Ubuntu, but I'm getting now a similar error like in Fedora 32+:

```
/usr/bin/ld: objects/if_python3.o: in function `call_PyObject_Free':
/root/vim/src/if_python3.c:796: undefined reference to `_PyObject_DebugFree'
```

Update: it was due my error in configuration option, but still I need to fix it.

**Comment by zdohnal** [comment]
Aha, those messages are warnings, it doesn't stop the compilation - now I see them too.

**Comment by zdohnal** [comment]
I'll clean the code and do the new pull request.
