### ISSUE TITLE
7.4.1314 console version fails to build on Windows 10 using MSVS 2015

### ISSUE THREAD

**Issue by nanis** [vim/vim#634]
GUI version builds with no issues.

I get:

```
eval.c
eval.c(7727): warning C4013: 'channel_close' undefined; assuming extern returning int
```

and then

```
eval.obj : error LNK2001: unresolved external symbol channel_close
vim.exe : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x460'
```

Unfortunately, I kept getting stuck with `git bisect`. I need to narrow down the range of commits, but, in the mean time, FYI.

Thank you.

**Comment by nanis** [comment]
Ah! I didn't have `CHANNEL=yes` on the command line. I just realized, the `GUI=yes` implies it.

I do have `NETBEANS=no`. So, if neither NETBEANS nor CHANNEL is enabled, shouldn't the console version skip everything channel related?

**Comment by brammool** [comment]
A. Sinan Unur wrote:

> Ah! I didn't have `CHANNEL=yes` on the command line. I just realized,
> the `GUI=yes` implies it.
> 
> I do have `NETBEANS=no`. So, if neither NETBEANS nor CHANNEL is
> enabled, shouldn't the console version skip everything channel
> related?

I assume this is because FEAT_JOB is defined.  That happens in
feature.h.  Patch 7.4.1316 should fix it.

## 

hundred-and-one symptoms of being an internet addict:
247. You use www.switchboard.com instead of dialing 411 and 555-12-12
     for directory assistance.

 /// Bram Moolenaar -- Bram@Moolenaar.net -- http://www.Moolenaar.net   \\
///        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ \\
\\  an exciting new programming language -- http://www.Zimbu.org        ///
 \\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by nanis** [comment]
I see now. Thank you. 7.4.1316 does indeed fix it.
