### ISSUE TITLE
Vim doesn't compile with Lua 5.3 on windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [vim/vim#329]
```
What steps will reproduce the problem?
1. Try to compile vim with Lua enabled (using MSVC or Mingw)

What is the expected output? What do you see instead?

Expected is a gvim.exe with +lua/dyn actual output is:

gobji386/if_lua.o:if_lua.c:(.text+0x35a2): undefined reference to 
`luaL_optlong' 


What version of the product are you using? On what operating system?

This was built with the hg tip version 
(c80ef2bf390ba312cbba7d7aa07a7ddd4ac92f43) of vim and lua 5.3.

Please provide any additional information below.

If one looks at lauxlib.h it's obvious that the definition of the missing 
luaL_optlong symbol is guarded by a ifdef LUA_COMPAT_APIINTCASTS 

Following patch fixes the build

diff -r c80ef2bf390b src/if_lua.c
--- a/src/if_lua.c  Wed Feb 04 23:08:02 2015 +0100
+++ b/src/if_lua.c  Wed Feb 11 16:52:12 2015 +0100
@@ -13,6 +13,7 @@

 #include <lua.h>
 #include <lualib.h>
+#define LUA_COMPAT_APIINTCASTS 1
 #include <lauxlib.h>

 /* Only do the following when the feature is enabled.  Needed for "make




```

Original issue reported on code.google.com by `mpc.jans...@gmail.com` on 11 Feb 2015 at 3:53
