### ISSUE TITLE
vim 9.1.1957 fails to compile with ruby4.0.0dev (2025-12-07)

### ISSUE THREAD

**Issue by mtasaka** [vim/vim#18884]
ruby 4.0.0 is to be released on 2025-Dec-25 and trying to prepare for it:

trying with `ruby 4.0.0dev (2025-12-07 master eafaff9443) +PRISM [x86_64-linux]` :
https://github.com/ruby/ruby/commit/eafaff9443daebba1f4e1a5b2a217b993f066360

vim 9.1.1957 fails to compile with configure option `--enable-rubyinterp=dynamic` added as:

```
gcc -c -I. -DDYNAMIC_RUBY_DLL=\"libruby.so.4.0\" -I/usr/include -I/usr/include -DRUBY_VERSION=40 -Iproto -DHAVE_CONFIG_H     -O2  -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -std=c17 -DSYS_VIMRC_FILE='"/etc/vimrc"'  -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1         -o objects/if_ruby.o if_ruby.c

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
NOTE: build date/time is fixed: Dec 05 2025 00:00:00
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

link.sh: $LINK_AS_NEEDED set to 'yes': invoking linker directly.
  gcc   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now    -Wl,--build-id=sha1   -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1    -L/usr/local/lib -o vim objects/alloc.o objects/arabic.o objects/arglist.o objects/autocmd.o objects/beval.o objects/buffer.o objects/change.o objects/blob.o objects/blowfish.o objects/cindent.o objects/clientserver.o objects/clipboard.o objects/cmdexpand.o objects/cmdhist.o objects/crypt.o objects/crypt_zip.o objects/debugger.o objects/dict.o objects/diff.o objects/digraph.o objects/drawline.o objects/drawscreen.o objects/edit.o objects/eval.o objects/evalbuffer.o objects/evalfunc.o objects/evalvars.o objects/evalwindow.o objects/ex_cmds.o objects/ex_cmds2.o objects/ex_docmd.o objects/ex_eval.o objects/ex_getln.o objects/fileio.o objects/filepath.o objects/findfile.o objects/float.o objects/fold.o objects/fuzzy.o objects/getchar.o objects/gc.o objects/gui_xim.o objects/hardcopy.o objects/hashtab.o objects/help.o objects/highlight.o objects/if_cscope.o objects/if_xcmdsrv.o objects/indent.o objects/insexpand.o objects/linematch.o objects/list.o objects/locale.o objects/logfile.o objects/map.o objects/mark.o objects/match.o objects/mbyte.o objects/memline.o objects/menu.o objects/misc1.o objects/misc2.o objects/mouse.o objects/move.o objects/normal.o objects/ops.o objects/option.o objects/optionstr.o objects/os_unix.o objects/pathdef.o objects/popupmenu.o objects/popupwin.o objects/profiler.o objects/pty.o objects/quickfix.o objects/regexp.o objects/register.o objects/screen.o objects/scriptfile.o objects/search.o objects/session.o objects/sha256.o objects/sign.o objects/sound.o objects/spell.o objects/spellfile.o objects/spellsuggest.o objects/strings.o objects/syntax.o objects/tabpanel.o objects/tag.o objects/term.o objects/terminal.o objects/testing.o objects/textformat.o objects/textobject.o objects/textprop.o objects/time.o objects/tuple.o objects/typval.o objects/ui.o objects/undo.o objects/usercmd.o objects/userfunc.o objects/version.o objects/vim9class.o objects/vim9cmds.o objects/vim9compile.o objects/vim9execute.o objects/vim9expr.o objects/vim9generics.o objects/vim9instr.o objects/vim9script.o objects/vim9type.o objects/viminfo.o objects/window.o objects/bufwrite.o  objects/vterm_encoding.o objects/vterm_keyboard.o objects/vterm_mouse.o objects/vterm_parser.o objects/vterm_pen.o objects/vterm_screen.o objects/vterm_state.o objects/vterm_unicode.o objects/vterm_vterm.o objects/if_lua.o  objects/if_perl.o  objects/if_python3.o  objects/if_ruby.o  objects/netbeans.o objects/job.o objects/channel.o objects/xdiffi.o objects/xemit.o objects/xprepare.o objects/xutils.o objects/xhistogram.o objects/xpatience.o   objects/charset.o objects/json.o objects/main.o objects/memfile.o objects/message.o         -lm  -lselinux  -lncurses -lsodium -lacl -lattr -lgpm           
/usr/bin/ld: objects/if_ruby.o: in function `rbimpl_check_typeddata':
/usr/include/ruby/internal/core/rtypeddata.h:625:(.text+0xf9b): undefined reference to `rb_check_typeddata'
/usr/bin/ld: /usr/include/ruby/internal/core/rtypeddata.h:625:(.text+0x1e5b): undefined reference to `rb_check_typeddata'
collect2: error: ld returned 1 exit status
link.sh: Linking failed
```

Most likely due to https://github.com/ruby/ruby/pull/15387

**Comment by mtasaka** [comment]
ruby 4.0 is formally released. Would you take a look at this?

**Comment by EnumeratedDev** [comment]
I've made a patch that seems to build with ruby 4.0, but it may cause issues elsewhere. I am not very knowledgeable in C and haven't worked in the vim codebase before. If people find that this works I can open a pull request to get it merged

[0001-Fix-building-with-ruby-4.0.patch](https://github.com/user-attachments/files/24384101/0001-Fix-building-with-ruby-4.0.patch)

**Comment by chrisbra** [comment]
This part of the patch looks wrong (double define):
```
+#    define define rb_check_typeddata		dll_rb_check_typeddata

```
Other than that, I'd say this looks reasonable, but I don't know the internals of the if_ruby interface much. So please create a PR with this patch so that our CI can at least verify it doesn't break anything obvious and others have a way to test it out more easily.

Thanks,
Chris

**Comment by ychin** [comment]
I don't think the previous fix worked (Vim would crash instead). Filed #19060 to fix it properly.
