### ISSUE TITLE
Vim 9 Does not compile on OSX 10.13 High Sierra

### ISSUE THREAD

**Issue by kneutron** [vim/vim#10646]
### Steps to reproduce

git clone https://github.com/vim/vim.git
cd vim/src && time make -s

2 errors generated.

---

### Expected behaviour

Compile and successful install

### Version of Vim

9

### Environment

OSX 10.13.6 High Sierra
Terminal = default
$TERM = screen

echo $BASH_VERSION
5.0.18(1)-release

### Logs and stack traces

```shell
git clone https://github.com/vim/vim.git
cd vim/src && time make -s

2 errors generated.

---

/opt/local/bin/desktop-file-validate
In file included from os_macosx.m:34:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:87:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:14:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/usr/include/hfs/hfs_format.h:794:2: error: unknown type name 'uuid_string_t'; did you mean 'io_string_t'?
        uuid_string_t   ext_jnl_uuid;
        ^
/usr/include/device/device_types.h:89:16: note: 'io_string_t' declared here
typedef char                    io_string_t[512];
                                ^
In file included from os_macosx.m:34:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:87:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:14:
In file included from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:208:
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/HFSVolumes.h:25:
/usr/include/hfs/hfs_format.h:796:20: error: use of undeclared identifier 'uuid_string_t'; did you mean 'uuid_variant'?
        char            reserved[JIB_RESERVED_SIZE];
                                 ^
/usr/include/hfs/hfs_format.h:787:61: note: expanded from macro 'JIB_RESERVED_SIZE'
#define JIB_RESERVED_SIZE  ((32*sizeof(u_int32_t)) - sizeof(uuid_string_t) - 48)
                                                            ^
/usr/local/include/uuid/uuid.h:113:12: note: 'uuid_variant' declared here
extern int uuid_variant(const uuid_t uu);
           ^
2 errors generated.
make: *** [objects/os_macosx.o] Error 1
```

**Comment by kneutron** [comment]
Thank you, correct. I have both brew and macports installed, so the fix was:

# mv -v /usr/local/include /usr/local/notinclude
/usr/local/include -> /usr/local/notinclude

...and redo **make -s** , which resulted in success. Obliged, especially for the quick response! :)
