### ISSUE TITLE
 os_mswin.c  msvc link LNK2001 error

### ISSUE THREAD

**Issue by MichelBudai** [vim/vim#17611]
### Steps to reproduce

I compiled vim 9.1.1481 using nmake -f make_mvc FEATURES=HUGE MBYTE=YES GETTEXT=no MAP=exports TERMINAL=yes PYTHON3=c.\Python313 DYNAMIC_PYTHON=yes PYTHON3 VER=313

The compiler cl C/C++ ver.19.29.30140 for x86 give these errors : 
os_win32.c)(1537) . error C2065: 'MOUSE_HWHEELED' : undefined identifier
os_win32.c)(1677) . error C2065: 'MOUSE_HWHEELED' : undefined identifier
os_win32.c)(1958) . error C2065: 'MOUSE_HWHEELED' : undefined identifier
os_win32.c)(1962) . error C2065: 'MOUSE_HWHEELED' : undefined identifier
...
os_mswin.c(1821): warning C4013: 'GetFinalPathNameByHandleW' undefined; assuming extern returning int
...

### Expected behaviour

The build on 20 june 2025 of vim 9.1.1472 version using the same compiler was ok.

### Version of Vim

9.1.1481

### Environment

WIn 10
cmd console
C/C++ ver.19.29.30140 for x86

### Logs and stack traces

```shell

```

**Comment by chrisbra** [comment]
That is strange, os_win32.c did not change and `MOUSE_HWHEELED` should be defined by your Windows build environment.

**Comment by MichelBudai** [comment]
> That is strange, os_win32.c did not change and `MOUSE_HWHEELED` should be defined by your Windows build environment.

Hello, Thank you for the quick answer, I will search.
Best regards,

**Comment by MichelBudai** [comment]
I solved the MOUSE_HWHEELED' : undefined identifier problem with , is defined in the header file wincontypes.h
But now I have a probleme with linking :
LINK : fatal error LNK1104: cannot open file 'python313.lib'
I have this file in libs folder in python 3 folder defined by PYTHON3=c.\Python313 DYNAMIC_PYTHON=yes PYTHON3_VER=313

But added Python313.lib folder in LIB env variable and another 1 link errors:
os_mswin.obj : error LNK2001: unresolved externql symbol _GetFinalPathNameByHandleW
vim.exe : fatal error LNK1120. 1 unresolved externals

This function GetFinalPathNameByHandleW is in fileapi.h in **Windows Kits\10\include\10.0.22000\um\**   folder

Added #include <fileapi.h> at the beginning of os_mswin,c and now the link is ok

**Comment by chrisbra** [comment]
closing this as not actionable.
