### PR TITLE
Fix building on Mac OS X 10.6 with MacPorts

### LINKED ISSUE #17678: FEAT_SOUND is only compatible with 10.7 or higher
### Steps to reproduce

1. install snow leopard
2. install xcode 4.2
3. install macports
4. type sudo port install -v build vim
5. you will see a failure that says:
`os_macosx.m:389:8: error: type arguments cannot be applied to non-parameterized class 'NSMutableDictionary'
static NSMutableDictionary<NSNumber*, NSSound*> *sounds_list = nil;
       ^                  ~~~~~~~~~~~~~~~~~~~~~
os_macosx.m:466:22: error: type arguments cannot be applied to non-parameterized class 'NSMutableDictionary'
            sounds_list = [[NSMutableDictionary<NSNumber*, NSSound*> alloc] init];
                            ^                  ~~~~~~~~~~~~~~~~~~~~~
os_macosx.m:468:2: error: expected method to write dictionary element not found on object of type 'NSMutableDictionary *'
        sounds_list[[NSNumber numberWithLong:sound_id]] = sound;
        ^
os_macosx.m:485:19: error: expected method to read dictionary element not found on object of type 'NSMutableDictionary *'
        NSSound *sound = sounds_list[[NSNumber numberWithLong:sound_id]];
                         ^
4 errors generated.
make[1]: *** [objects/os_macosx.o] Error 1
make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_editors_vim/vim/work/vim-9.1.1128/src'
`

### Expected behaviour

vim should build and install on 10.6 without issue

### Version of Vim

9.1.11288

### Environment

APPUL MAC OSX 10.6.8
BASH 5.2.37(1)-release

### Logs and stack traces

```shell
the solution is simple:

just change line 184 in vim.h:


# if defined(FEAT_HUGE) && !defined(FEAT_SOUND) && \
  defined(__clang_major__) && __clang_major__ >= 7 && \
  defined(MAC_OS_X_VERSION_MIN_REQUIRED) && MAC_OS_X_VERSION_MIN_REQUIRED >= 1060


to


# if defined(FEAT_HUGE) && !defined(FEAT_SOUND) && \
  defined(__clang_major__) && __clang_major__ >= 7 && \
  defined(MAC_OS_X_VERSION_MIN_REQUIRED) && MAC_OS_X_VERSION_MIN_REQUIRED >= 1070


and it build/works fine.
```

### PR DESCRIPTION
**Pull request by haihige**
Closes #17678. The original author of sound support on Mac OS (#11274) wrote some checks that would skip the sound feature from being built if the older, stock version of clang was used on Snow Leopard. However, if MacPorts is used to build on 10.6 with a newer version of clang, it fails because of the use of generics and subscripting.

This change takes this case into consideration, and allows vim +huge +sound to build on 10.6 using MacPorts by utilizing the older style of Objective-C syntax.

### CODE REVIEW

**Comment by sevan** [comment]
The logic should be inverted so the fallthrough case is for all OS versions beyond and the if condition should be for checking for 1060 explicitly.

**Comment by chrisbra** [comment]
I think this is way around is fine, as the same style is used elsewhere in this file. @ychin any comments please ?

**Comment by ychin** [comment]
> However, if MacPorts is used to build on 10.6 with a newer version of clang, it fails because of the use of generics and subscripting

I don't think this statement is correct. If MacPorts is using an actual new version of clang, it would be able to handle generics. The issue was that MacPorts is using an old version of clang, but it's using vanilla clang with a different versioning scheme than Apple clang, making the `__clang_major__` detection not work correctly. That's why I kept asking for what the `__clang_major__` was in the other thread but didn't get a response.

I think the "correct" fix would be to check for the correct clang version and use that (and use `__apple_build_version__` to distinguish between Apple clang and vanilla clang). But using SDK works I guess. A lot of times it's already used as proxy for other information.

Personally I would rather just disable sound for 10.6 to avoid having to write more code, but this patch does allow more people to use the sound feature (albeit at a very old OS version) so I'm fine with it.

**Comment by haihige** [comment]
> > However, if MacPorts is used to build on 10.6 with a newer version of clang, it fails because of the use of generics and subscripting
> 
> I don't think this statement is correct. If MacPorts is using an actual new version of clang, it would be able to handle generics. The issue was that MacPorts is using an old version of clang, but it's using vanilla clang with a different versioning scheme than Apple clang, making the `__clang_major__` detection not work correctly. That's why I kept asking for what the `__clang_major__` was in the other thread but didn't get a response.

@ychin You're right, on my 10.6 systems it says that [`clang-mp-11`](https://ports.macports.org/port/clang-11/details/) is used for building and `--version` prints 11.1.0, but it fails to build and I'm not sure why. I even tried [`clang-mp-14`](https://ports.macports.org/port/clang-14/details/) and that failed too!

> Personally I would rather just disable sound for 10.6 to avoid having to write more code, but this patch does allow more people to use the sound feature (albeit at a very old OS version) so I'm fine with it.

I also thought about that, but it's only 16 lines of code for the best release of Mac OS X. :) It seems like there may be a conflict with the compilers on 10.6, but since the only Snow Leopard users who would probably install a recent version of Vim are using MacPorts to install it, I thought it was worth fixing it this way rather than figuring out what's going on with the MacPorts version of clang; especially since this is one of the few important programs that fails to build on that version.

**Comment by ychin** [comment]
So, I don't have an issue with this idea per se. But I think you should probably use `MAC_OS_X_VERSION_MAX_ALLOWED` instead of `MAC_OS_X_VERSION_MIN_REQUIRED`. In case you are not aware, the "max allowed" is the one that actually indicates the SDK / platform that you can building against, whereas `MAC_OS_X_VERSION_MIN_REQUIRED` is just the "deployment target" that could be set much lower than the SDK you are using, and is a user-configurable variable. I previously had to fix an issue related to this where someone made the mistake of using "min required" and ended up setting this too high (see #13251). Apple allows you to use newer sets of SDKs and set a lower deployment target so a single binary and work in multiple OS versions (this is how most prebuild binaries on macOS works).

Using "max allowed" sounds more correct to me in this case. You may want to double check that it works in MacPort of course, since it seems like they are using non-standard compiler toolchain and I'm not sure what they set these values to.

**Comment by ychin** [comment]
Also, with this change you are introducing another check for whether generic is supported, and I don't love how we are checking this in two different places. We are checking whether `__clang_major__ >= 7` in the header, then you are implicitly checking for it again in the .c file for another reason. While it's a "couple lines" of code these things add up later when we are trying to figure out the intent and refactor them.

If you want to add the check I would rather do:

1. Remove the `__clang_major__` check in the header.
2. In the .c file, make the check to be something like this:
```
#if defined(__apple_build_version__) && defined(__clang_major__) && __clang_major__ >= 7
  // Use the original version that uses generics
#else
  // Use the non-generics version
#endif
```

This seems the cleanest way to resolve it without having to hack.

But then I'm ok with just straight-up removing the generics version at this point. It's only syntactical sugar and internally Objective-C works mostly the same. I don't think it optimizes it to a much faster version if at all. I'm always of the philosophy that less code / less complexity is better than more.

---

Just for summary / for the record: I think we should just remove the generic version and remove all these checks and ifdefs.

**Comment by sevan** [comment]
> I previously had to fix an issue related to this where someone made the mistake of using "min required" and ended up setting this too high (see #13251). 

Indeed, the functionality was introduced in 10.6 but the code would only compile with clang on 10.10, so I set the min required to 10.10.

**Comment by haihige** [comment]
> But I think you should probably use `MAC_OS_X_VERSION_MAX_ALLOWED` instead of `MAC_OS_X_VERSION_MIN_REQUIRED`. In case you are not aware, the "max allowed" is the one that actually indicates the SDK / platform that you can building against, whereas `MAC_OS_X_VERSION_MIN_REQUIRED` is just the "deployment target" that could be set much lower than the SDK you are using, and is a user-configurable variable.

Thank you for taking the time to explain that! It's been a long time since I've looked at Objective-C and Cocoa development, so I appreciate the help as I relearn it.

> Using "max allowed" sounds more correct to me in this case. You may want to double check that it works in MacPort of course, since it seems like they are using non-standard compiler toolchain and I'm not sure what they set these values to.

I tried that out and it worked, but I think your latter solution is better (see below).

> But then I'm ok with just straight-up removing the generics version at this point. It's only syntactical sugar and internally Objective-C works mostly the same.
> ...
> I'm always of the philosophy that less code / less complexity is better than more.
> 
> Just for summary / for the record: I think we should just remove the generic version and remove all these checks and ifdefs.

Completely agree! I didn't know if this would be okay at first, but that sounds like the way to go.

I've just committed an update for `os_macosx.m`.

**Comment by chrisbra** [comment]
thanks
